#
# AssetsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER SerialList
No description available.
.PARAMETER Quantity
No description available.
.PARAMETER Serial
No description available.
.PARAMETER DestinationLocationId
No description available.
.PARAMETER DestinationContactId
No description available.
.PARAMETER DestinationDepartmentId
No description available.
.OUTPUTS

AssetTransferUpdateDto<PSCustomObject>
#>

function Initialize-AssetTransferUpdateDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SerialList},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Quantity},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Serial},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DestinationLocationId},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DestinationContactId},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DestinationDepartmentId}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => AssetTransferUpdateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "serialList" = ${SerialList}
            "quantity" = ${Quantity}
            "serial" = ${Serial}
            "destinationLocationId" = ${DestinationLocationId}
            "destinationContactId" = ${DestinationContactId}
            "destinationDepartmentId" = ${DestinationDepartmentId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AssetTransferUpdateDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to AssetTransferUpdateDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AssetTransferUpdateDto<PSCustomObject>
#>
function ConvertFrom-JsonToAssetTransferUpdateDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => AssetTransferUpdateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AssetTransferUpdateDto
        $AllProperties = ("serialList", "quantity", "serial", "destinationLocationId", "destinationContactId", "destinationDepartmentId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "serialList"))) { #optional property not found
            $SerialList = $null
        } else {
            $SerialList = $JsonParameters.PSobject.Properties["serialList"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "quantity"))) { #optional property not found
            $Quantity = $null
        } else {
            $Quantity = $JsonParameters.PSobject.Properties["quantity"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "serial"))) { #optional property not found
            $Serial = $null
        } else {
            $Serial = $JsonParameters.PSobject.Properties["serial"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "destinationLocationId"))) { #optional property not found
            $DestinationLocationId = $null
        } else {
            $DestinationLocationId = $JsonParameters.PSobject.Properties["destinationLocationId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "destinationContactId"))) { #optional property not found
            $DestinationContactId = $null
        } else {
            $DestinationContactId = $JsonParameters.PSobject.Properties["destinationContactId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "destinationDepartmentId"))) { #optional property not found
            $DestinationDepartmentId = $null
        } else {
            $DestinationDepartmentId = $JsonParameters.PSobject.Properties["destinationDepartmentId"].value
        }

        $PSO = [PSCustomObject]@{
            "serialList" = ${SerialList}
            "quantity" = ${Quantity}
            "serial" = ${Serial}
            "destinationLocationId" = ${DestinationLocationId}
            "destinationContactId" = ${DestinationContactId}
            "destinationDepartmentId" = ${DestinationDepartmentId}
        }

        return $PSO
    }

}

