#
# TenantsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TenantTeamUpdateDto' {
    Context 'TenantTeamUpdateDto' {
        It 'Initialize-TenantTeamUpdateDto' {
            # a simple test to create an object
            #$NewObject = Initialize-TenantTeamUpdateDto -Id "TEST_VALUE" -Timestamp "TEST_VALUE" -BusinessID "TEST_VALUE" -BusinessProfileRecordID "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -AvatarURL "TEST_VALUE" -IsPublic "TEST_VALUE" -BusinessUnitID "TEST_VALUE" -OrganizationProfileID "TEST_VALUE"
            #$NewObject | Should -BeOfType TenantTeamUpdateDto
            #$NewObject.property | Should -Be 0
        }
    }
}
