#
# LogisticsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.1.2.5401
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Timestamp
No description available.
.PARAMETER Quantity
No description available.
.PARAMETER ItemId
No description available.
.PARAMETER WarehouseId
No description available.
.PARAMETER ItemRestockId
No description available.
.PARAMETER OrderItemRecordId
No description available.
.PARAMETER TenantId
No description available.
.OUTPUTS

ItemRestockEntryDto<PSCustomObject>
#>

function Initialize-ItemRestockEntryDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${Timestamp},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${Quantity},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ItemId},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${WarehouseId},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ItemRestockId},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${OrderItemRecordId},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TenantId}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ItemRestockEntryDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "quantity" = ${Quantity}
            "itemId" = ${ItemId}
            "warehouseId" = ${WarehouseId}
            "itemRestockId" = ${ItemRestockId}
            "orderItemRecordId" = ${OrderItemRecordId}
            "tenantId" = ${TenantId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ItemRestockEntryDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to ItemRestockEntryDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ItemRestockEntryDto<PSCustomObject>
#>
function ConvertFrom-JsonToItemRestockEntryDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ItemRestockEntryDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ItemRestockEntryDto
        $AllProperties = ("id", "timestamp", "quantity", "itemId", "warehouseId", "itemRestockId", "orderItemRecordId", "tenantId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timestamp"))) { #optional property not found
            $Timestamp = $null
        } else {
            $Timestamp = $JsonParameters.PSobject.Properties["timestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "quantity"))) { #optional property not found
            $Quantity = $null
        } else {
            $Quantity = $JsonParameters.PSobject.Properties["quantity"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "itemId"))) { #optional property not found
            $ItemId = $null
        } else {
            $ItemId = $JsonParameters.PSobject.Properties["itemId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "warehouseId"))) { #optional property not found
            $WarehouseId = $null
        } else {
            $WarehouseId = $JsonParameters.PSobject.Properties["warehouseId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "itemRestockId"))) { #optional property not found
            $ItemRestockId = $null
        } else {
            $ItemRestockId = $JsonParameters.PSobject.Properties["itemRestockId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "orderItemRecordId"))) { #optional property not found
            $OrderItemRecordId = $null
        } else {
            $OrderItemRecordId = $JsonParameters.PSobject.Properties["orderItemRecordId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tenantId"))) { #optional property not found
            $TenantId = $null
        } else {
            $TenantId = $JsonParameters.PSobject.Properties["tenantId"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "quantity" = ${Quantity}
            "itemId" = ${ItemId}
            "warehouseId" = ${WarehouseId}
            "itemRestockId" = ${ItemRestockId}
            "orderItemRecordId" = ${OrderItemRecordId}
            "tenantId" = ${TenantId}
        }

        return $PSO
    }

}

