#
# LocationsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Email
No description available.
.PARAMETER ResetCode
No description available.
.PARAMETER NewPassword
No description available.
.OUTPUTS

ResetPasswordRequest<PSCustomObject>
#>

function Initialize-ResetPasswordRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Email},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ResetCode},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${NewPassword}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ResetPasswordRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "email" = ${Email}
            "resetCode" = ${ResetCode}
            "newPassword" = ${NewPassword}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ResetPasswordRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to ResetPasswordRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ResetPasswordRequest<PSCustomObject>
#>
function ConvertFrom-JsonToResetPasswordRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ResetPasswordRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ResetPasswordRequest
        $AllProperties = ("email", "resetCode", "newPassword")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'email' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "email"))) {
            throw "Error! JSON cannot be serialized due to the required property 'email' missing."
        } else {
            $Email = $JsonParameters.PSobject.Properties["email"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "resetCode"))) {
            throw "Error! JSON cannot be serialized due to the required property 'resetCode' missing."
        } else {
            $ResetCode = $JsonParameters.PSobject.Properties["resetCode"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "newPassword"))) {
            throw "Error! JSON cannot be serialized due to the required property 'newPassword' missing."
        } else {
            $NewPassword = $JsonParameters.PSobject.Properties["newPassword"].value
        }

        $PSO = [PSCustomObject]@{
            "email" = ${Email}
            "resetCode" = ${ResetCode}
            "newPassword" = ${NewPassword}
        }

        return $PSO
    }

}

