#
# AssetsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'AssetCreateDto' {
    Context 'AssetCreateDto' {
        It 'Initialize-AssetCreateDto' {
            # a simple test to create an object
            #$NewObject = Initialize-AssetCreateDto -Id "TEST_VALUE" -Timestamp "TEST_VALUE" -BusinessId "TEST_VALUE" -BusinessProfileRecordId "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -AssetClass "TEST_VALUE" -AssetOwner "TEST_VALUE" -IsExistingAsset "TEST_VALUE" -CalculateDepreciation "TEST_VALUE" -AllowMonthlyDepreciation "TEST_VALUE" -OpeningDepreciation "TEST_VALUE" -PurchaseDate "TEST_VALUE" -PurchasePrice "TEST_VALUE" -CurrencyId "TEST_VALUE" -ItemId "TEST_VALUE" -AssetCategoryId "TEST_VALUE" -PurchaseInvoiceId "TEST_VALUE" -PurchaseReceiptId "TEST_VALUE" -AssetLocationId "TEST_VALUE" -ContactId "TEST_VALUE" -OrganizationDepartmentId "TEST_VALUE"
            #$NewObject | Should -BeOfType AssetCreateDto
            #$NewObject.property | Should -Be 0
        }
    }
}
