#
# AssetsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PatchOperation' {
    Context 'PatchOperation' {
        It 'Initialize-PatchOperation' {
            # a simple test to create an object
            #$NewObject = Initialize-PatchOperation -Op "TEST_VALUE" -Path "TEST_VALUE" -VarFrom "TEST_VALUE" -Value "TEST_VALUE"
            #$NewObject | Should -BeOfType PatchOperation
            #$NewObject.property | Should -Be 0
        }
    }
}
