#
# AccountingService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.1.2.5257
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'AccountCreateDto' {
    Context 'AccountCreateDto' {
        It 'Initialize-AccountCreateDto' {
            # a simple test to create an object
            #$NewObject = Initialize-AccountCreateDto -Id "TEST_VALUE" -Timestamp "TEST_VALUE" -Group "TEST_VALUE" -Frozen "TEST_VALUE" -Name "TEST_VALUE" -Code "TEST_VALUE" -Path "TEST_VALUE" -Prefix "TEST_VALUE" -TenantId "TEST_VALUE" -CurrencyId "TEST_VALUE" -EnrollmentId "TEST_VALUE" -AccountTypeId "TEST_VALUE" -ParentAccountId "TEST_VALUE" -AccountCategory "TEST_VALUE"
            #$NewObject | Should -BeOfType AccountCreateDto
            #$NewObject.property | Should -Be 0
        }
    }
}
