#
# AccountingService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'AccountRelationDto' {
    Context 'AccountRelationDto' {
        It 'Initialize-AccountRelationDto' {
            # a simple test to create an object
            #$NewObject = Initialize-AccountRelationDto -Id "TEST_VALUE" -Timestamp "TEST_VALUE" -AccountId "TEST_VALUE" -TenantId "TEST_VALUE" -EnrollmentId "TEST_VALUE"
            #$NewObject | Should -BeOfType AccountRelationDto
            #$NewObject.property | Should -Be 0
        }
    }
}
