#
# AccountingService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'FinancialBookUpdateDto' {
    Context 'FinancialBookUpdateDto' {
        It 'Initialize-FinancialBookUpdateDto' {
            # a simple test to create an object
            #$NewObject = Initialize-FinancialBookUpdateDto -Name "TEST_VALUE" -Description "TEST_VALUE" -TenantId "TEST_VALUE"
            #$NewObject | Should -BeOfType FinancialBookUpdateDto
            #$NewObject.property | Should -Be 0
        }
    }
}
