#
# AccountingService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ItemTaxPolicyRecordUpdateDto' {
    Context 'ItemTaxPolicyRecordUpdateDto' {
        It 'Initialize-ItemTaxPolicyRecordUpdateDto' {
            # a simple test to create an object
            #$NewObject = Initialize-ItemTaxPolicyRecordUpdateDto -Id "TEST_VALUE" -Timestamp "TEST_VALUE" -TaxPolicyId "TEST_VALUE" -ItemPriceId "TEST_VALUE" -ItemId "TEST_VALUE"
            #$NewObject | Should -BeOfType ItemTaxPolicyRecordUpdateDto
            #$NewObject.property | Should -Be 0
        }
    }
}
