#
# AccountingService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.1.2.5257
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ShareTransferCreateDto' {
    Context 'ShareTransferCreateDto' {
        It 'Initialize-ShareTransferCreateDto' {
            # a simple test to create an object
            #$NewObject = Initialize-ShareTransferCreateDto -Id "TEST_VALUE" -Timestamp "TEST_VALUE" -Description "TEST_VALUE" -Value "TEST_VALUE" -NewShareHolderId "TEST_VALUE" -FormerShareHolderId "TEST_VALUE" -ShareTransferReasonId "TEST_VALUE" -EnrollmentId "TEST_VALUE" -TenantId "TEST_VALUE"
            #$NewObject | Should -BeOfType ShareTransferCreateDto
            #$NewObject.property | Should -Be 0
        }
    }
}
