#
# ServicesService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ServiceLevelAgreementDtoIReadOnlyListEnvelope' {
    Context 'ServiceLevelAgreementDtoIReadOnlyListEnvelope' {
        It 'Initialize-ServiceLevelAgreementDtoIReadOnlyListEnvelope' {
            # a simple test to create an object
            #$NewObject = Initialize-ServiceLevelAgreementDtoIReadOnlyListEnvelope -IsSuccess "TEST_VALUE" -ErrorMessage "TEST_VALUE" -CorrelationId "TEST_VALUE" -Timestamp "TEST_VALUE" -ActivityId "TEST_VALUE" -Result "TEST_VALUE"
            #$NewObject | Should -BeOfType ServiceLevelAgreementDtoIReadOnlyListEnvelope
            #$NewObject.property | Should -Be 0
        }
    }
}
