#
# LearningService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Title
No description available.
.PARAMETER Description
No description available.
.PARAMETER ImageURL
No description available.
.PARAMETER IsFeatured
No description available.
.OUTPUTS

CourseCategoryUpdateDto<PSCustomObject>
#>

function Initialize-CourseCategoryUpdateDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Title},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ImageURL},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsFeatured}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => CourseCategoryUpdateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "title" = ${Title}
            "description" = ${Description}
            "imageURL" = ${ImageURL}
            "isFeatured" = ${IsFeatured}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CourseCategoryUpdateDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to CourseCategoryUpdateDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CourseCategoryUpdateDto<PSCustomObject>
#>
function ConvertFrom-JsonToCourseCategoryUpdateDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => CourseCategoryUpdateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CourseCategoryUpdateDto
        $AllProperties = ("title", "description", "imageURL", "isFeatured")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "title"))) { #optional property not found
            $Title = $null
        } else {
            $Title = $JsonParameters.PSobject.Properties["title"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "imageURL"))) { #optional property not found
            $ImageURL = $null
        } else {
            $ImageURL = $JsonParameters.PSobject.Properties["imageURL"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isFeatured"))) { #optional property not found
            $IsFeatured = $null
        } else {
            $IsFeatured = $JsonParameters.PSobject.Properties["isFeatured"].value
        }

        $PSO = [PSCustomObject]@{
            "title" = ${Title}
            "description" = ${Description}
            "imageURL" = ${ImageURL}
            "isFeatured" = ${IsFeatured}
        }

        return $PSO
    }

}

