#
# IntelligenceService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER FileId
No description available.
.PARAMETER Name
No description available.
.PARAMETER ContentType
No description available.
.PARAMETER Length
No description available.
.OUTPUTS

ConversationAttachmentUploadResultDto<PSCustomObject>
#>

function Initialize-ConversationAttachmentUploadResultDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${FileId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ContentType},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${Length}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ConversationAttachmentUploadResultDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "fileId" = ${FileId}
            "name" = ${Name}
            "contentType" = ${ContentType}
            "length" = ${Length}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ConversationAttachmentUploadResultDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to ConversationAttachmentUploadResultDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ConversationAttachmentUploadResultDto<PSCustomObject>
#>
function ConvertFrom-JsonToConversationAttachmentUploadResultDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ConversationAttachmentUploadResultDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ConversationAttachmentUploadResultDto
        $AllProperties = ("fileId", "name", "contentType", "length")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "fileId"))) { #optional property not found
            $FileId = $null
        } else {
            $FileId = $JsonParameters.PSobject.Properties["fileId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "contentType"))) { #optional property not found
            $ContentType = $null
        } else {
            $ContentType = $JsonParameters.PSobject.Properties["contentType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "length"))) { #optional property not found
            $Length = $null
        } else {
            $Length = $JsonParameters.PSobject.Properties["length"].value
        }

        $PSO = [PSCustomObject]@{
            "fileId" = ${FileId}
            "name" = ${Name}
            "contentType" = ${ContentType}
            "length" = ${Length}
        }

        return $PSO
    }

}

