#
# CatalogService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ItemGoogleCategoriesApi' {
    Context 'Get-AllItemGoogleCategoriesAsync' {
        It 'Test Get-AllItemGoogleCategoriesAsync' {
            #$TestResult = Get-AllItemGoogleCategoriesAsync -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ChildrenItemGoogleCategoriesByIdAsync' {
        It 'Test Get-ChildrenItemGoogleCategoriesByIdAsync' {
            #$TestResult = Get-ChildrenItemGoogleCategoriesByIdAsync -ItemCategoryId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ItemGoogleCategoriesAsync' {
        It 'Test Get-ItemGoogleCategoriesAsync' {
            #$TestResult = Get-ItemGoogleCategoriesAsync -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ItemGoogleCategoriesCountAsync' {
        It 'Test Get-ItemGoogleCategoriesCountAsync' {
            #$TestResult = Get-ItemGoogleCategoriesCountAsync -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ItemGoogleCategoriesTreeAsync' {
        It 'Test Get-ItemGoogleCategoriesTreeAsync' {
            #$TestResult = Get-ItemGoogleCategoriesTreeAsync -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ItemGoogleCategoryByIdAsync' {
        It 'Test Get-ItemGoogleCategoryByIdAsync' {
            #$TestResult = Get-ItemGoogleCategoryByIdAsync -ItemCategoryId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-RootItemGoogleCategoriesAsync' {
        It 'Test Get-RootItemGoogleCategoriesAsync' {
            #$TestResult = Get-RootItemGoogleCategoriesAsync -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-MapItemGoogleCategoriesTreeAsync' {
        It 'Test Invoke-MapItemGoogleCategoriesTreeAsync' {
            #$TestResult = Invoke-MapItemGoogleCategoriesTreeAsync -TenantId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
