#
# HrmsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Remote
No description available.
.PARAMETER Type
No description available.
.PARAMETER Title
No description available.
.PARAMETER Description
No description available.
.PARAMETER ExpectedDeliveryDate
No description available.
.PARAMETER EmployerProfileId
No description available.
.PARAMETER MinBudget
No description available.
.PARAMETER MaxBudget
No description available.
.PARAMETER CurrencyId
No description available.
.PARAMETER CountryId
No description available.
.PARAMETER CountryStateId
No description available.
.PARAMETER CityId
No description available.
.PARAMETER Location
No description available.
.PARAMETER ExternalUrl
No description available.
.PARAMETER VarData
No description available.
.PARAMETER DataLabel
No description available.
.PARAMETER Data1
No description available.
.PARAMETER Data1Label
No description available.
.PARAMETER Data2
No description available.
.PARAMETER Data2Label
No description available.
.PARAMETER Data3
No description available.
.PARAMETER Data3Label
No description available.
.PARAMETER Data4
No description available.
.PARAMETER Data4Label
No description available.
.PARAMETER Data5
No description available.
.PARAMETER Data5Label
No description available.
.PARAMETER Data6
No description available.
.PARAMETER Data6Label
No description available.
.PARAMETER Data7
No description available.
.PARAMETER Data7Label
No description available.
.PARAMETER Data8
No description available.
.PARAMETER Data8Label
No description available.
.PARAMETER Data9
No description available.
.PARAMETER Data9Label
No description available.
.OUTPUTS

GigUpdateDto<PSCustomObject>
#>

function Initialize-GigUpdateDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Remote},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Type},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Title},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${ExpectedDeliveryDate},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${EmployerProfileId},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${MinBudget},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${MaxBudget},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CurrencyId},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CountryId},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CountryStateId},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CityId},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Location},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ExternalUrl},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${VarData},
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DataLabel},
        [Parameter(Position = 16, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Data1},
        [Parameter(Position = 17, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Data1Label},
        [Parameter(Position = 18, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Data2},
        [Parameter(Position = 19, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Data2Label},
        [Parameter(Position = 20, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Data3},
        [Parameter(Position = 21, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Data3Label},
        [Parameter(Position = 22, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Data4},
        [Parameter(Position = 23, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Data4Label},
        [Parameter(Position = 24, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Data5},
        [Parameter(Position = 25, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Data5Label},
        [Parameter(Position = 26, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Data6},
        [Parameter(Position = 27, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Data6Label},
        [Parameter(Position = 28, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Data7},
        [Parameter(Position = 29, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Data7Label},
        [Parameter(Position = 30, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Data8},
        [Parameter(Position = 31, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Data8Label},
        [Parameter(Position = 32, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Data9},
        [Parameter(Position = 33, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Data9Label}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => GigUpdateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "remote" = ${Remote}
            "type" = ${Type}
            "title" = ${Title}
            "description" = ${Description}
            "expectedDeliveryDate" = ${ExpectedDeliveryDate}
            "employerProfileId" = ${EmployerProfileId}
            "minBudget" = ${MinBudget}
            "maxBudget" = ${MaxBudget}
            "currencyId" = ${CurrencyId}
            "countryId" = ${CountryId}
            "countryStateId" = ${CountryStateId}
            "cityId" = ${CityId}
            "location" = ${Location}
            "externalUrl" = ${ExternalUrl}
            "data" = ${VarData}
            "dataLabel" = ${DataLabel}
            "data1" = ${Data1}
            "data1Label" = ${Data1Label}
            "data2" = ${Data2}
            "data2Label" = ${Data2Label}
            "data3" = ${Data3}
            "data3Label" = ${Data3Label}
            "data4" = ${Data4}
            "data4Label" = ${Data4Label}
            "data5" = ${Data5}
            "data5Label" = ${Data5Label}
            "data6" = ${Data6}
            "data6Label" = ${Data6Label}
            "data7" = ${Data7}
            "data7Label" = ${Data7Label}
            "data8" = ${Data8}
            "data8Label" = ${Data8Label}
            "data9" = ${Data9}
            "data9Label" = ${Data9Label}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to GigUpdateDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to GigUpdateDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

GigUpdateDto<PSCustomObject>
#>
function ConvertFrom-JsonToGigUpdateDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => GigUpdateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in GigUpdateDto
        $AllProperties = ("remote", "type", "title", "description", "expectedDeliveryDate", "employerProfileId", "minBudget", "maxBudget", "currencyId", "countryId", "countryStateId", "cityId", "location", "externalUrl", "data", "dataLabel", "data1", "data1Label", "data2", "data2Label", "data3", "data3Label", "data4", "data4Label", "data5", "data5Label", "data6", "data6Label", "data7", "data7Label", "data8", "data8Label", "data9", "data9Label")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "remote"))) { #optional property not found
            $Remote = $null
        } else {
            $Remote = $JsonParameters.PSobject.Properties["remote"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "type"))) { #optional property not found
            $Type = $null
        } else {
            $Type = $JsonParameters.PSobject.Properties["type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "title"))) { #optional property not found
            $Title = $null
        } else {
            $Title = $JsonParameters.PSobject.Properties["title"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "expectedDeliveryDate"))) { #optional property not found
            $ExpectedDeliveryDate = $null
        } else {
            $ExpectedDeliveryDate = $JsonParameters.PSobject.Properties["expectedDeliveryDate"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "employerProfileId"))) { #optional property not found
            $EmployerProfileId = $null
        } else {
            $EmployerProfileId = $JsonParameters.PSobject.Properties["employerProfileId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "minBudget"))) { #optional property not found
            $MinBudget = $null
        } else {
            $MinBudget = $JsonParameters.PSobject.Properties["minBudget"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "maxBudget"))) { #optional property not found
            $MaxBudget = $null
        } else {
            $MaxBudget = $JsonParameters.PSobject.Properties["maxBudget"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "currencyId"))) { #optional property not found
            $CurrencyId = $null
        } else {
            $CurrencyId = $JsonParameters.PSobject.Properties["currencyId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "countryId"))) { #optional property not found
            $CountryId = $null
        } else {
            $CountryId = $JsonParameters.PSobject.Properties["countryId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "countryStateId"))) { #optional property not found
            $CountryStateId = $null
        } else {
            $CountryStateId = $JsonParameters.PSobject.Properties["countryStateId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "cityId"))) { #optional property not found
            $CityId = $null
        } else {
            $CityId = $JsonParameters.PSobject.Properties["cityId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "location"))) { #optional property not found
            $Location = $null
        } else {
            $Location = $JsonParameters.PSobject.Properties["location"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "externalUrl"))) { #optional property not found
            $ExternalUrl = $null
        } else {
            $ExternalUrl = $JsonParameters.PSobject.Properties["externalUrl"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data"))) { #optional property not found
            $VarData = $null
        } else {
            $VarData = $JsonParameters.PSobject.Properties["data"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "dataLabel"))) { #optional property not found
            $DataLabel = $null
        } else {
            $DataLabel = $JsonParameters.PSobject.Properties["dataLabel"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data1"))) { #optional property not found
            $Data1 = $null
        } else {
            $Data1 = $JsonParameters.PSobject.Properties["data1"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data1Label"))) { #optional property not found
            $Data1Label = $null
        } else {
            $Data1Label = $JsonParameters.PSobject.Properties["data1Label"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data2"))) { #optional property not found
            $Data2 = $null
        } else {
            $Data2 = $JsonParameters.PSobject.Properties["data2"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data2Label"))) { #optional property not found
            $Data2Label = $null
        } else {
            $Data2Label = $JsonParameters.PSobject.Properties["data2Label"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data3"))) { #optional property not found
            $Data3 = $null
        } else {
            $Data3 = $JsonParameters.PSobject.Properties["data3"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data3Label"))) { #optional property not found
            $Data3Label = $null
        } else {
            $Data3Label = $JsonParameters.PSobject.Properties["data3Label"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data4"))) { #optional property not found
            $Data4 = $null
        } else {
            $Data4 = $JsonParameters.PSobject.Properties["data4"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data4Label"))) { #optional property not found
            $Data4Label = $null
        } else {
            $Data4Label = $JsonParameters.PSobject.Properties["data4Label"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data5"))) { #optional property not found
            $Data5 = $null
        } else {
            $Data5 = $JsonParameters.PSobject.Properties["data5"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data5Label"))) { #optional property not found
            $Data5Label = $null
        } else {
            $Data5Label = $JsonParameters.PSobject.Properties["data5Label"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data6"))) { #optional property not found
            $Data6 = $null
        } else {
            $Data6 = $JsonParameters.PSobject.Properties["data6"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data6Label"))) { #optional property not found
            $Data6Label = $null
        } else {
            $Data6Label = $JsonParameters.PSobject.Properties["data6Label"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data7"))) { #optional property not found
            $Data7 = $null
        } else {
            $Data7 = $JsonParameters.PSobject.Properties["data7"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data7Label"))) { #optional property not found
            $Data7Label = $null
        } else {
            $Data7Label = $JsonParameters.PSobject.Properties["data7Label"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data8"))) { #optional property not found
            $Data8 = $null
        } else {
            $Data8 = $JsonParameters.PSobject.Properties["data8"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data8Label"))) { #optional property not found
            $Data8Label = $null
        } else {
            $Data8Label = $JsonParameters.PSobject.Properties["data8Label"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data9"))) { #optional property not found
            $Data9 = $null
        } else {
            $Data9 = $JsonParameters.PSobject.Properties["data9"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data9Label"))) { #optional property not found
            $Data9Label = $null
        } else {
            $Data9Label = $JsonParameters.PSobject.Properties["data9Label"].value
        }

        $PSO = [PSCustomObject]@{
            "remote" = ${Remote}
            "type" = ${Type}
            "title" = ${Title}
            "description" = ${Description}
            "expectedDeliveryDate" = ${ExpectedDeliveryDate}
            "employerProfileId" = ${EmployerProfileId}
            "minBudget" = ${MinBudget}
            "maxBudget" = ${MaxBudget}
            "currencyId" = ${CurrencyId}
            "countryId" = ${CountryId}
            "countryStateId" = ${CountryStateId}
            "cityId" = ${CityId}
            "location" = ${Location}
            "externalUrl" = ${ExternalUrl}
            "data" = ${VarData}
            "dataLabel" = ${DataLabel}
            "data1" = ${Data1}
            "data1Label" = ${Data1Label}
            "data2" = ${Data2}
            "data2Label" = ${Data2Label}
            "data3" = ${Data3}
            "data3Label" = ${Data3Label}
            "data4" = ${Data4}
            "data4Label" = ${Data4Label}
            "data5" = ${Data5}
            "data5Label" = ${Data5Label}
            "data6" = ${Data6}
            "data6Label" = ${Data6Label}
            "data7" = ${Data7}
            "data7Label" = ${Data7Label}
            "data8" = ${Data8}
            "data8Label" = ${Data8Label}
            "data9" = ${Data9}
            "data9Label" = ${Data9Label}
        }

        return $PSO
    }

}

