#
# HrmsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Justification
No description available.
.PARAMETER Approved
No description available.
.PARAMETER OnReview
No description available.
.PARAMETER LeaveTypeId
No description available.
.PARAMETER EmployeeProfileId
No description available.
.OUTPUTS

LeaveApplicationUpdateDto<PSCustomObject>
#>

function Initialize-LeaveApplicationUpdateDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Justification},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Approved},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${OnReview},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${LeaveTypeId},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${EmployeeProfileId}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => LeaveApplicationUpdateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "justification" = ${Justification}
            "approved" = ${Approved}
            "onReview" = ${OnReview}
            "leaveTypeId" = ${LeaveTypeId}
            "employeeProfileId" = ${EmployeeProfileId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to LeaveApplicationUpdateDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to LeaveApplicationUpdateDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

LeaveApplicationUpdateDto<PSCustomObject>
#>
function ConvertFrom-JsonToLeaveApplicationUpdateDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => LeaveApplicationUpdateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in LeaveApplicationUpdateDto
        $AllProperties = ("justification", "approved", "onReview", "leaveTypeId", "employeeProfileId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "justification"))) { #optional property not found
            $Justification = $null
        } else {
            $Justification = $JsonParameters.PSobject.Properties["justification"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "approved"))) { #optional property not found
            $Approved = $null
        } else {
            $Approved = $JsonParameters.PSobject.Properties["approved"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "onReview"))) { #optional property not found
            $OnReview = $null
        } else {
            $OnReview = $JsonParameters.PSobject.Properties["onReview"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "leaveTypeId"))) { #optional property not found
            $LeaveTypeId = $null
        } else {
            $LeaveTypeId = $JsonParameters.PSobject.Properties["leaveTypeId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "employeeProfileId"))) { #optional property not found
            $EmployeeProfileId = $null
        } else {
            $EmployeeProfileId = $JsonParameters.PSobject.Properties["employeeProfileId"].value
        }

        $PSO = [PSCustomObject]@{
            "justification" = ${Justification}
            "approved" = ${Approved}
            "onReview" = ${OnReview}
            "leaveTypeId" = ${LeaveTypeId}
            "employeeProfileId" = ${EmployeeProfileId}
        }

        return $PSO
    }

}

