#
# LicensingService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'LicensingCertificateDtoCollectionQueryParameters' {
    Context 'LicensingCertificateDtoCollectionQueryParameters' {
        It 'Initialize-LicensingCertificateDtoCollectionQueryParameters' {
            # a simple test to create an object
            #$NewObject = Initialize-LicensingCertificateDtoCollectionQueryParameters -Top "TEST_VALUE" -Skip "TEST_VALUE" -Count "TEST_VALUE" -VarFilter "TEST_VALUE" -OrderBy "TEST_VALUE" -Search "TEST_VALUE" -Select "TEST_VALUE" -Expand "TEST_VALUE" -IsEmpty "TEST_VALUE"
            #$NewObject | Should -BeOfType LicensingCertificateDtoCollectionQueryParameters
            #$NewObject.property | Should -Be 0
        }
    }
}
