#
# BlockchainsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.1.2.5532
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER VarFilter
No description available.
.PARAMETER Apply
No description available.
.PARAMETER Compute
No description available.
.PARAMETER Search
No description available.
.PARAMETER OrderBy
No description available.
.PARAMETER Top
No description available.
.PARAMETER Skip
No description available.
.PARAMETER Select
No description available.
.PARAMETER Expand
No description available.
.PARAMETER Count
No description available.
.PARAMETER Format
No description available.
.PARAMETER SkipToken
No description available.
.PARAMETER DeltaToken
No description available.
.OUTPUTS

ODataRawQueryOptions<PSCustomObject>
#>

function Initialize-ODataRawQueryOptions {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${VarFilter},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Apply},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Compute},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Search},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${OrderBy},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Top},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Skip},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Select},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Expand},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Count},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Format},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SkipToken},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DeltaToken}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ODataRawQueryOptions' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "filter" = ${VarFilter}
            "apply" = ${Apply}
            "compute" = ${Compute}
            "search" = ${Search}
            "orderBy" = ${OrderBy}
            "top" = ${Top}
            "skip" = ${Skip}
            "select" = ${Select}
            "expand" = ${Expand}
            "count" = ${Count}
            "format" = ${Format}
            "skipToken" = ${SkipToken}
            "deltaToken" = ${DeltaToken}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ODataRawQueryOptions<PSCustomObject>

.DESCRIPTION

Convert from JSON to ODataRawQueryOptions<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ODataRawQueryOptions<PSCustomObject>
#>
function ConvertFrom-JsonToODataRawQueryOptions {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ODataRawQueryOptions' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ODataRawQueryOptions
        $AllProperties = ("filter", "apply", "compute", "search", "orderBy", "top", "skip", "select", "expand", "count", "format", "skipToken", "deltaToken")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "filter"))) { #optional property not found
            $VarFilter = $null
        } else {
            $VarFilter = $JsonParameters.PSobject.Properties["filter"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "apply"))) { #optional property not found
            $Apply = $null
        } else {
            $Apply = $JsonParameters.PSobject.Properties["apply"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "compute"))) { #optional property not found
            $Compute = $null
        } else {
            $Compute = $JsonParameters.PSobject.Properties["compute"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "search"))) { #optional property not found
            $Search = $null
        } else {
            $Search = $JsonParameters.PSobject.Properties["search"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "orderBy"))) { #optional property not found
            $OrderBy = $null
        } else {
            $OrderBy = $JsonParameters.PSobject.Properties["orderBy"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "top"))) { #optional property not found
            $Top = $null
        } else {
            $Top = $JsonParameters.PSobject.Properties["top"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "skip"))) { #optional property not found
            $Skip = $null
        } else {
            $Skip = $JsonParameters.PSobject.Properties["skip"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "select"))) { #optional property not found
            $Select = $null
        } else {
            $Select = $JsonParameters.PSobject.Properties["select"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "expand"))) { #optional property not found
            $Expand = $null
        } else {
            $Expand = $JsonParameters.PSobject.Properties["expand"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "count"))) { #optional property not found
            $Count = $null
        } else {
            $Count = $JsonParameters.PSobject.Properties["count"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "format"))) { #optional property not found
            $Format = $null
        } else {
            $Format = $JsonParameters.PSobject.Properties["format"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "skipToken"))) { #optional property not found
            $SkipToken = $null
        } else {
            $SkipToken = $JsonParameters.PSobject.Properties["skipToken"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "deltaToken"))) { #optional property not found
            $DeltaToken = $null
        } else {
            $DeltaToken = $JsonParameters.PSobject.Properties["deltaToken"].value
        }

        $PSO = [PSCustomObject]@{
            "filter" = ${VarFilter}
            "apply" = ${Apply}
            "compute" = ${Compute}
            "search" = ${Search}
            "orderBy" = ${OrderBy}
            "top" = ${Top}
            "skip" = ${Skip}
            "select" = ${Select}
            "expand" = ${Expand}
            "count" = ${Count}
            "format" = ${Format}
            "skipToken" = ${SkipToken}
            "deltaToken" = ${DeltaToken}
        }

        return $PSO
    }

}

