#
# InvoicingService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.1.4089
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'InvoiceAdjustmentCreateDto' {
    Context 'InvoiceAdjustmentCreateDto' {
        It 'Initialize-InvoiceAdjustmentCreateDto' {
            # a simple test to create an object
            #$NewObject = Initialize-InvoiceAdjustmentCreateDto -Id "TEST_VALUE" -Timestamp "TEST_VALUE" -TenantId "TEST_VALUE" -InvoiceId "TEST_VALUE" -CurrencyId "TEST_VALUE" -EnrollmentId "TEST_VALUE" -Description "TEST_VALUE" -SurchargePercent "TEST_VALUE" -SurchargeAmount "TEST_VALUE" -DiscountPercent "TEST_VALUE" -DiscountAmount "TEST_VALUE" -TotalSurcharge "TEST_VALUE" -TotalDiscount "TEST_VALUE" -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType InvoiceAdjustmentCreateDto
            #$NewObject.property | Should -Be 0
        }
    }
}
