#
# TenantsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'OptionsApi' {
    Context 'New-TenantOption' {
        It 'Test New-TenantOption' {
            #$TestResult = New-TenantOption -TenantId "TEST_VALUE" -Key "TEST_VALUE" -PortalId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE" -OptionCreateDto "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeleteTenantOption' {
        It 'Test Invoke-DeleteTenantOption' {
            #$TestResult = Invoke-DeleteTenantOption -TenantId "TEST_VALUE" -OptionId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TenantOptionById' {
        It 'Test Get-TenantOptionById' {
            #$TestResult = Get-TenantOptionById -TenantId "TEST_VALUE" -OptionId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TenantOptionByKey' {
        It 'Test Get-TenantOptionByKey' {
            #$TestResult = Get-TenantOptionByKey -TenantId "TEST_VALUE" -Key "TEST_VALUE" -PortalId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TenantOptions' {
        It 'Test Get-TenantOptions' {
            #$TestResult = Get-TenantOptions -TenantId "TEST_VALUE" -PortalId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TenantOptionsCount' {
        It 'Test Get-TenantOptionsCount' {
            #$TestResult = Get-TenantOptionsCount -TenantId "TEST_VALUE" -PortalId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-TenantOption' {
        It 'Test Update-TenantOption' {
            #$TestResult = Update-TenantOption -TenantId "TEST_VALUE" -OptionId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE" -OptionUpdateDto "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-UpsertTenantOption' {
        It 'Test Invoke-UpsertTenantOption' {
            #$TestResult = Invoke-UpsertTenantOption -TenantId "TEST_VALUE" -Key "TEST_VALUE" -PortalId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE" -OptionUpdateDto "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
