#
# SocialService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Timestamp
No description available.
.PARAMETER Reaction
No description available.
.PARAMETER ReactionValue
No description available.
.PARAMETER SocialProfileId
No description available.
.PARAMETER SocialProfileName
No description available.
.PARAMETER SocialProfileAvatarUrl
No description available.
.OUTPUTS

SocialReactionDto<PSCustomObject>
#>

function Initialize-SocialReactionDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${Timestamp},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("Like", "Happy", "HaHa", "Love", "Sad", "Angry", "Wow", "Afraid")]
        [String]
        ${Reaction},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ReactionValue},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SocialProfileId},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SocialProfileName},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SocialProfileAvatarUrl}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => SocialReactionDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "reaction" = ${Reaction}
            "reactionValue" = ${ReactionValue}
            "socialProfileId" = ${SocialProfileId}
            "socialProfileName" = ${SocialProfileName}
            "socialProfileAvatarUrl" = ${SocialProfileAvatarUrl}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to SocialReactionDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to SocialReactionDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

SocialReactionDto<PSCustomObject>
#>
function ConvertFrom-JsonToSocialReactionDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => SocialReactionDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in SocialReactionDto
        $AllProperties = ("id", "timestamp", "reaction", "reactionValue", "socialProfileId", "socialProfileName", "socialProfileAvatarUrl")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timestamp"))) { #optional property not found
            $Timestamp = $null
        } else {
            $Timestamp = $JsonParameters.PSobject.Properties["timestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "reaction"))) { #optional property not found
            $Reaction = $null
        } else {
            $Reaction = $JsonParameters.PSobject.Properties["reaction"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "reactionValue"))) { #optional property not found
            $ReactionValue = $null
        } else {
            $ReactionValue = $JsonParameters.PSobject.Properties["reactionValue"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "socialProfileId"))) { #optional property not found
            $SocialProfileId = $null
        } else {
            $SocialProfileId = $JsonParameters.PSobject.Properties["socialProfileId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "socialProfileName"))) { #optional property not found
            $SocialProfileName = $null
        } else {
            $SocialProfileName = $JsonParameters.PSobject.Properties["socialProfileName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "socialProfileAvatarUrl"))) { #optional property not found
            $SocialProfileAvatarUrl = $null
        } else {
            $SocialProfileAvatarUrl = $JsonParameters.PSobject.Properties["socialProfileAvatarUrl"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "reaction" = ${Reaction}
            "reactionValue" = ${ReactionValue}
            "socialProfileId" = ${SocialProfileId}
            "socialProfileName" = ${SocialProfileName}
            "socialProfileAvatarUrl" = ${SocialProfileAvatarUrl}
        }

        return $PSO
    }

}

