#
# ServicesService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER ServiceId
No description available.
.PARAMETER ServiceLevelId
No description available.
.PARAMETER ContactId
No description available.
.OUTPUTS

ServiceLevelAgreementUpdateDto<PSCustomObject>
#>

function Initialize-ServiceLevelAgreementUpdateDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ServiceId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ServiceLevelId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ContactId}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ServiceLevelAgreementUpdateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "serviceId" = ${ServiceId}
            "serviceLevelId" = ${ServiceLevelId}
            "contactId" = ${ContactId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ServiceLevelAgreementUpdateDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to ServiceLevelAgreementUpdateDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ServiceLevelAgreementUpdateDto<PSCustomObject>
#>
function ConvertFrom-JsonToServiceLevelAgreementUpdateDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ServiceLevelAgreementUpdateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ServiceLevelAgreementUpdateDto
        $AllProperties = ("serviceId", "serviceLevelId", "contactId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "serviceId"))) { #optional property not found
            $ServiceId = $null
        } else {
            $ServiceId = $JsonParameters.PSobject.Properties["serviceId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "serviceLevelId"))) { #optional property not found
            $ServiceLevelId = $null
        } else {
            $ServiceLevelId = $JsonParameters.PSobject.Properties["serviceLevelId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "contactId"))) { #optional property not found
            $ContactId = $null
        } else {
            $ContactId = $JsonParameters.PSobject.Properties["contactId"].value
        }

        $PSO = [PSCustomObject]@{
            "serviceId" = ${ServiceId}
            "serviceLevelId" = ${ServiceLevelId}
            "contactId" = ${ContactId}
        }

        return $PSO
    }

}

