#
# TrustService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER ProviderName
No description available.
.PARAMETER ProviderMode
No description available.
.PARAMETER SigningProfileId
No description available.
.PARAMETER SigningCertificateId
No description available.
.OUTPUTS

ExecuteSigningRequestDto<PSCustomObject>
#>

function Initialize-ExecuteSigningRequestDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ProviderName},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ProviderMode},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SigningProfileId},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SigningCertificateId}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ExecuteSigningRequestDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $ProviderName) {
            throw "invalid value for 'ProviderName', 'ProviderName' cannot be null."
        }

        if ($ProviderName.length -lt 1) {
            throw "invalid value for 'ProviderName', the character length must be great than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "providerName" = ${ProviderName}
            "providerMode" = ${ProviderMode}
            "signingProfileId" = ${SigningProfileId}
            "signingCertificateId" = ${SigningCertificateId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ExecuteSigningRequestDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to ExecuteSigningRequestDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ExecuteSigningRequestDto<PSCustomObject>
#>
function ConvertFrom-JsonToExecuteSigningRequestDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ExecuteSigningRequestDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ExecuteSigningRequestDto
        $AllProperties = ("providerName", "providerMode", "signingProfileId", "signingCertificateId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'providerName' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "providerName"))) {
            throw "Error! JSON cannot be serialized due to the required property 'providerName' missing."
        } else {
            $ProviderName = $JsonParameters.PSobject.Properties["providerName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "providerMode"))) { #optional property not found
            $ProviderMode = $null
        } else {
            $ProviderMode = $JsonParameters.PSobject.Properties["providerMode"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "signingProfileId"))) { #optional property not found
            $SigningProfileId = $null
        } else {
            $SigningProfileId = $JsonParameters.PSobject.Properties["signingProfileId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "signingCertificateId"))) { #optional property not found
            $SigningCertificateId = $null
        } else {
            $SigningCertificateId = $JsonParameters.PSobject.Properties["signingCertificateId"].value
        }

        $PSO = [PSCustomObject]@{
            "providerName" = ${ProviderName}
            "providerMode" = ${ProviderMode}
            "signingProfileId" = ${SigningProfileId}
            "signingCertificateId" = ${SigningCertificateId}
        }

        return $PSO
    }

}

