#
# PricingService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.1.4089
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'DiscountListCreateDto' {
    Context 'DiscountListCreateDto' {
        It 'Initialize-DiscountListCreateDto' {
            # a simple test to create an object
            #$NewObject = Initialize-DiscountListCreateDto -Id "TEST_VALUE" -Timestamp "TEST_VALUE" -Name "TEST_VALUE" -CurrencyId "TEST_VALUE" -TenantId "TEST_VALUE" -EnrolmentId "TEST_VALUE"
            #$NewObject | Should -BeOfType DiscountListCreateDto
            #$NewObject.property | Should -Be 0
        }
    }
}
