#
# SystemService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Timestamp
No description available.
.PARAMETER Key
No description available.
.PARAMETER Value
No description available.
.PARAMETER PortalId
No description available.
.PARAMETER Frozen
No description available.
.PARAMETER Autoload
No description available.
.PARAMETER Transient
No description available.
.PARAMETER Expiration
No description available.
.OUTPUTS

OptionDto<PSCustomObject>
#>

function Initialize-OptionDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${Timestamp},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Key},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Value},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${PortalId},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Frozen},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Autoload},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Transient},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Expiration}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => OptionDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "key" = ${Key}
            "value" = ${Value}
            "portalId" = ${PortalId}
            "frozen" = ${Frozen}
            "autoload" = ${Autoload}
            "transient" = ${Transient}
            "expiration" = ${Expiration}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to OptionDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to OptionDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

OptionDto<PSCustomObject>
#>
function ConvertFrom-JsonToOptionDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => OptionDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OptionDto
        $AllProperties = ("id", "timestamp", "key", "value", "portalId", "frozen", "autoload", "transient", "expiration")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timestamp"))) { #optional property not found
            $Timestamp = $null
        } else {
            $Timestamp = $JsonParameters.PSobject.Properties["timestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "key"))) { #optional property not found
            $Key = $null
        } else {
            $Key = $JsonParameters.PSobject.Properties["key"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "value"))) { #optional property not found
            $Value = $null
        } else {
            $Value = $JsonParameters.PSobject.Properties["value"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "portalId"))) { #optional property not found
            $PortalId = $null
        } else {
            $PortalId = $JsonParameters.PSobject.Properties["portalId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "frozen"))) { #optional property not found
            $Frozen = $null
        } else {
            $Frozen = $JsonParameters.PSobject.Properties["frozen"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "autoload"))) { #optional property not found
            $Autoload = $null
        } else {
            $Autoload = $JsonParameters.PSobject.Properties["autoload"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "transient"))) { #optional property not found
            $Transient = $null
        } else {
            $Transient = $JsonParameters.PSobject.Properties["transient"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "expiration"))) { #optional property not found
            $Expiration = $null
        } else {
            $Expiration = $JsonParameters.PSobject.Properties["expiration"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "key" = ${Key}
            "value" = ${Value}
            "portalId" = ${PortalId}
            "frozen" = ${Frozen}
            "autoload" = ${Autoload}
            "transient" = ${Transient}
            "expiration" = ${Expiration}
        }

        return $PSO
    }

}

