#
# SystemService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Timestamp
No description available.
.PARAMETER TenantId
No description available.
.PARAMETER Kind
No description available.
.PARAMETER MessageType
No description available.
.PARAMETER Status
No description available.
.PARAMETER Attempts
No description available.
.PARAMETER MaxAttempts
No description available.
.PARAMETER FailureCode
No description available.
.PARAMETER FailureReason
No description available.
.PARAMETER IdempotencyKey
No description available.
.PARAMETER CorrelationId
No description available.
.PARAMETER LockedBy
No description available.
.PARAMETER LockedUntilUtc
No description available.
.PARAMETER AvailableAtUtc
No description available.
.PARAMETER CreatedAtUtc
No description available.
.PARAMETER LastAttemptAtUtc
No description available.
.PARAMETER ProcessedAtUtc
No description available.
.PARAMETER FailedAtUtc
No description available.
.OUTPUTS

OutboxMessageDto<PSCustomObject>
#>

function Initialize-OutboxMessageDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${Timestamp},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TenantId},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("Event", "Command")]
        [String]
        ${Kind},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${MessageType},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("Pending", "Processing", "Succeeded", "Failed", "DeadLettered", "Cancelled")]
        [String]
        ${Status},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Attempts},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${MaxAttempts},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${FailureCode},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${FailureReason},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${IdempotencyKey},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CorrelationId},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${LockedBy},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${LockedUntilUtc},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${AvailableAtUtc},
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${CreatedAtUtc},
        [Parameter(Position = 16, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${LastAttemptAtUtc},
        [Parameter(Position = 17, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${ProcessedAtUtc},
        [Parameter(Position = 18, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${FailedAtUtc}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => OutboxMessageDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "tenantId" = ${TenantId}
            "kind" = ${Kind}
            "messageType" = ${MessageType}
            "status" = ${Status}
            "attempts" = ${Attempts}
            "maxAttempts" = ${MaxAttempts}
            "failureCode" = ${FailureCode}
            "failureReason" = ${FailureReason}
            "idempotencyKey" = ${IdempotencyKey}
            "correlationId" = ${CorrelationId}
            "lockedBy" = ${LockedBy}
            "lockedUntilUtc" = ${LockedUntilUtc}
            "availableAtUtc" = ${AvailableAtUtc}
            "createdAtUtc" = ${CreatedAtUtc}
            "lastAttemptAtUtc" = ${LastAttemptAtUtc}
            "processedAtUtc" = ${ProcessedAtUtc}
            "failedAtUtc" = ${FailedAtUtc}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to OutboxMessageDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to OutboxMessageDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

OutboxMessageDto<PSCustomObject>
#>
function ConvertFrom-JsonToOutboxMessageDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => OutboxMessageDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OutboxMessageDto
        $AllProperties = ("id", "timestamp", "tenantId", "kind", "messageType", "status", "attempts", "maxAttempts", "failureCode", "failureReason", "idempotencyKey", "correlationId", "lockedBy", "lockedUntilUtc", "availableAtUtc", "createdAtUtc", "lastAttemptAtUtc", "processedAtUtc", "failedAtUtc")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timestamp"))) { #optional property not found
            $Timestamp = $null
        } else {
            $Timestamp = $JsonParameters.PSobject.Properties["timestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tenantId"))) { #optional property not found
            $TenantId = $null
        } else {
            $TenantId = $JsonParameters.PSobject.Properties["tenantId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "kind"))) { #optional property not found
            $Kind = $null
        } else {
            $Kind = $JsonParameters.PSobject.Properties["kind"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "messageType"))) { #optional property not found
            $MessageType = $null
        } else {
            $MessageType = $JsonParameters.PSobject.Properties["messageType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "status"))) { #optional property not found
            $Status = $null
        } else {
            $Status = $JsonParameters.PSobject.Properties["status"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "attempts"))) { #optional property not found
            $Attempts = $null
        } else {
            $Attempts = $JsonParameters.PSobject.Properties["attempts"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "maxAttempts"))) { #optional property not found
            $MaxAttempts = $null
        } else {
            $MaxAttempts = $JsonParameters.PSobject.Properties["maxAttempts"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "failureCode"))) { #optional property not found
            $FailureCode = $null
        } else {
            $FailureCode = $JsonParameters.PSobject.Properties["failureCode"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "failureReason"))) { #optional property not found
            $FailureReason = $null
        } else {
            $FailureReason = $JsonParameters.PSobject.Properties["failureReason"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "idempotencyKey"))) { #optional property not found
            $IdempotencyKey = $null
        } else {
            $IdempotencyKey = $JsonParameters.PSobject.Properties["idempotencyKey"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "correlationId"))) { #optional property not found
            $CorrelationId = $null
        } else {
            $CorrelationId = $JsonParameters.PSobject.Properties["correlationId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "lockedBy"))) { #optional property not found
            $LockedBy = $null
        } else {
            $LockedBy = $JsonParameters.PSobject.Properties["lockedBy"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "lockedUntilUtc"))) { #optional property not found
            $LockedUntilUtc = $null
        } else {
            $LockedUntilUtc = $JsonParameters.PSobject.Properties["lockedUntilUtc"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "availableAtUtc"))) { #optional property not found
            $AvailableAtUtc = $null
        } else {
            $AvailableAtUtc = $JsonParameters.PSobject.Properties["availableAtUtc"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "createdAtUtc"))) { #optional property not found
            $CreatedAtUtc = $null
        } else {
            $CreatedAtUtc = $JsonParameters.PSobject.Properties["createdAtUtc"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "lastAttemptAtUtc"))) { #optional property not found
            $LastAttemptAtUtc = $null
        } else {
            $LastAttemptAtUtc = $JsonParameters.PSobject.Properties["lastAttemptAtUtc"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "processedAtUtc"))) { #optional property not found
            $ProcessedAtUtc = $null
        } else {
            $ProcessedAtUtc = $JsonParameters.PSobject.Properties["processedAtUtc"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "failedAtUtc"))) { #optional property not found
            $FailedAtUtc = $null
        } else {
            $FailedAtUtc = $JsonParameters.PSobject.Properties["failedAtUtc"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "tenantId" = ${TenantId}
            "kind" = ${Kind}
            "messageType" = ${MessageType}
            "status" = ${Status}
            "attempts" = ${Attempts}
            "maxAttempts" = ${MaxAttempts}
            "failureCode" = ${FailureCode}
            "failureReason" = ${FailureReason}
            "idempotencyKey" = ${IdempotencyKey}
            "correlationId" = ${CorrelationId}
            "lockedBy" = ${LockedBy}
            "lockedUntilUtc" = ${LockedUntilUtc}
            "availableAtUtc" = ${AvailableAtUtc}
            "createdAtUtc" = ${CreatedAtUtc}
            "lastAttemptAtUtc" = ${LastAttemptAtUtc}
            "processedAtUtc" = ${ProcessedAtUtc}
            "failedAtUtc" = ${FailedAtUtc}
        }

        return $PSO
    }

}

