#
# LogisticsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.1.2.5401
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ItemPackingSlipEntryDtoEnvelope' {
    Context 'ItemPackingSlipEntryDtoEnvelope' {
        It 'Initialize-ItemPackingSlipEntryDtoEnvelope' {
            # a simple test to create an object
            #$NewObject = Initialize-ItemPackingSlipEntryDtoEnvelope -IsSuccess "TEST_VALUE" -ErrorMessage "TEST_VALUE" -CorrelationId "TEST_VALUE" -Timestamp "TEST_VALUE" -ActivityId "TEST_VALUE" -Result "TEST_VALUE"
            #$NewObject | Should -BeOfType ItemPackingSlipEntryDtoEnvelope
            #$NewObject.property | Should -Be 0
        }
    }
}
