#
# LogisticsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.1.2.5401
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ItemPickListDto' {
    Context 'ItemPickListDto' {
        It 'Initialize-ItemPickListDto' {
            # a simple test to create an object
            #$NewObject = Initialize-ItemPickListDto -Id "TEST_VALUE" -Timestamp "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -OrderId "TEST_VALUE" -TenantId "TEST_VALUE"
            #$NewObject | Should -BeOfType ItemPickListDto
            #$NewObject.property | Should -Be 0
        }
    }
}
