#
# LogisticsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.1.2.5401
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ItemRetainSampleCreateDto' {
    Context 'ItemRetainSampleCreateDto' {
        It 'Initialize-ItemRetainSampleCreateDto' {
            # a simple test to create an object
            #$NewObject = Initialize-ItemRetainSampleCreateDto -Id "TEST_VALUE" -Timestamp "TEST_VALUE" -WarehouseId "TEST_VALUE" -ItemId "TEST_VALUE"
            #$NewObject | Should -BeOfType ItemRetainSampleCreateDto
            #$NewObject.property | Should -Be 0
        }
    }
}
