#
# LogisticsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.1.2.5401
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TruckDriverCreateDto' {
    Context 'TruckDriverCreateDto' {
        It 'Initialize-TruckDriverCreateDto' {
            # a simple test to create an object
            #$NewObject = Initialize-TruckDriverCreateDto -Id "TEST_VALUE" -Timestamp "TEST_VALUE" -Name "TEST_VALUE" -LicenseNumber "TEST_VALUE" -LicenseClass "TEST_VALUE" -Phone "TEST_VALUE" -Email "TEST_VALUE" -ContactId "TEST_VALUE" -ShippingCourierId "TEST_VALUE" -AdrCertified "TEST_VALUE" -LicenseExpiryDate "TEST_VALUE" -MedicalExamExpiryDate "TEST_VALUE" -NationalIdNumber "TEST_VALUE" -Notes "TEST_VALUE"
            #$NewObject | Should -BeOfType TruckDriverCreateDto
            #$NewObject.property | Should -Be 0
        }
    }
}
