#
# LogisticsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.1.2.5401
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'VoyageUpdateDto' {
    Context 'VoyageUpdateDto' {
        It 'Initialize-VoyageUpdateDto' {
            # a simple test to create an object
            #$NewObject = Initialize-VoyageUpdateDto -VoyageNumber "TEST_VALUE" -Title "TEST_VALUE" -Description "TEST_VALUE" -VoyageDirection "TEST_VALUE" -DepartureDate "TEST_VALUE" -ArrivalDate "TEST_VALUE" -VesselId "TEST_VALUE"
            #$NewObject | Should -BeOfType VoyageUpdateDto
            #$NewObject.property | Should -Be 0
        }
    }
}
