#
# CrmService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Timestamp
No description available.
.PARAMETER ContactId
No description available.
.PARAMETER Address
No description available.
.PARAMETER Label
No description available.
.PARAMETER IsPrimary
No description available.
.OUTPUTS

ContactEmailCreateDto<PSCustomObject>
#>

function Initialize-ContactEmailCreateDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${Timestamp},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ContactId},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Address},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Label},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsPrimary}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ContactEmailCreateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "contactId" = ${ContactId}
            "address" = ${Address}
            "label" = ${Label}
            "isPrimary" = ${IsPrimary}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ContactEmailCreateDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to ContactEmailCreateDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ContactEmailCreateDto<PSCustomObject>
#>
function ConvertFrom-JsonToContactEmailCreateDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ContactEmailCreateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ContactEmailCreateDto
        $AllProperties = ("id", "timestamp", "contactId", "address", "label", "isPrimary")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timestamp"))) { #optional property not found
            $Timestamp = $null
        } else {
            $Timestamp = $JsonParameters.PSobject.Properties["timestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "contactId"))) { #optional property not found
            $ContactId = $null
        } else {
            $ContactId = $JsonParameters.PSobject.Properties["contactId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "address"))) { #optional property not found
            $Address = $null
        } else {
            $Address = $JsonParameters.PSobject.Properties["address"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "label"))) { #optional property not found
            $Label = $null
        } else {
            $Label = $JsonParameters.PSobject.Properties["label"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isPrimary"))) { #optional property not found
            $IsPrimary = $null
        } else {
            $IsPrimary = $JsonParameters.PSobject.Properties["isPrimary"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "contactId" = ${ContactId}
            "address" = ${Address}
            "label" = ${Label}
            "isPrimary" = ${IsPrimary}
        }

        return $PSO
    }

}

