#
# TenantsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Timestamp
No description available.
.PARAMETER ChildTenantId
No description available.
.PARAMETER OwnershipPercentage
No description available.
.OUTPUTS

BusinessRelationshipCreateDto<PSCustomObject>
#>

function Initialize-BusinessRelationshipCreateDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${Timestamp},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ChildTenantId},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${OwnershipPercentage}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => BusinessRelationshipCreateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "childTenantId" = ${ChildTenantId}
            "ownershipPercentage" = ${OwnershipPercentage}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to BusinessRelationshipCreateDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to BusinessRelationshipCreateDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

BusinessRelationshipCreateDto<PSCustomObject>
#>
function ConvertFrom-JsonToBusinessRelationshipCreateDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => BusinessRelationshipCreateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in BusinessRelationshipCreateDto
        $AllProperties = ("id", "timestamp", "childTenantId", "ownershipPercentage")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timestamp"))) { #optional property not found
            $Timestamp = $null
        } else {
            $Timestamp = $JsonParameters.PSobject.Properties["timestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "childTenantId"))) { #optional property not found
            $ChildTenantId = $null
        } else {
            $ChildTenantId = $JsonParameters.PSobject.Properties["childTenantId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ownershipPercentage"))) { #optional property not found
            $OwnershipPercentage = $null
        } else {
            $OwnershipPercentage = $JsonParameters.PSobject.Properties["ownershipPercentage"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "childTenantId" = ${ChildTenantId}
            "ownershipPercentage" = ${OwnershipPercentage}
        }

        return $PSO
    }

}

