#
# TenantsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.1.2.5532
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Timestamp
No description available.
.PARAMETER TenantId
No description available.
.PARAMETER EnrollmentId
No description available.
.PARAMETER Name
No description available.
.PARAMETER Description
No description available.
.PARAMETER Disabled
No description available.
.PARAMETER OrganizationProfileId
No description available.
.PARAMETER ParentDepartmentId
No description available.
.OUTPUTS

TenantDepartmentDto<PSCustomObject>
#>

function Initialize-TenantDepartmentDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${Timestamp},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TenantId},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${EnrollmentId},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Disabled},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${OrganizationProfileId},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ParentDepartmentId}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => TenantDepartmentDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "tenantId" = ${TenantId}
            "enrollmentId" = ${EnrollmentId}
            "name" = ${Name}
            "description" = ${Description}
            "disabled" = ${Disabled}
            "organizationProfileId" = ${OrganizationProfileId}
            "parentDepartmentId" = ${ParentDepartmentId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to TenantDepartmentDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to TenantDepartmentDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

TenantDepartmentDto<PSCustomObject>
#>
function ConvertFrom-JsonToTenantDepartmentDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => TenantDepartmentDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in TenantDepartmentDto
        $AllProperties = ("id", "timestamp", "tenantId", "enrollmentId", "name", "description", "disabled", "organizationProfileId", "parentDepartmentId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timestamp"))) { #optional property not found
            $Timestamp = $null
        } else {
            $Timestamp = $JsonParameters.PSobject.Properties["timestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tenantId"))) { #optional property not found
            $TenantId = $null
        } else {
            $TenantId = $JsonParameters.PSobject.Properties["tenantId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "enrollmentId"))) { #optional property not found
            $EnrollmentId = $null
        } else {
            $EnrollmentId = $JsonParameters.PSobject.Properties["enrollmentId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "disabled"))) { #optional property not found
            $Disabled = $null
        } else {
            $Disabled = $JsonParameters.PSobject.Properties["disabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "organizationProfileId"))) { #optional property not found
            $OrganizationProfileId = $null
        } else {
            $OrganizationProfileId = $JsonParameters.PSobject.Properties["organizationProfileId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "parentDepartmentId"))) { #optional property not found
            $ParentDepartmentId = $null
        } else {
            $ParentDepartmentId = $JsonParameters.PSobject.Properties["parentDepartmentId"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "tenantId" = ${TenantId}
            "enrollmentId" = ${EnrollmentId}
            "name" = ${Name}
            "description" = ${Description}
            "disabled" = ${Disabled}
            "organizationProfileId" = ${OrganizationProfileId}
            "parentDepartmentId" = ${ParentDepartmentId}
        }

        return $PSO
    }

}

