#
# TenantsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Name
No description available.
.PARAMETER Description
No description available.
.PARAMETER Disabled
No description available.
.PARAMETER OrganizationProfileId
No description available.
.PARAMETER ParentDepartmentId
No description available.
.OUTPUTS

TenantDepartmentUpdateDto<PSCustomObject>
#>

function Initialize-TenantDepartmentUpdateDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Disabled},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${OrganizationProfileId},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ParentDepartmentId}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => TenantDepartmentUpdateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "name" = ${Name}
            "description" = ${Description}
            "disabled" = ${Disabled}
            "organizationProfileId" = ${OrganizationProfileId}
            "parentDepartmentId" = ${ParentDepartmentId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to TenantDepartmentUpdateDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to TenantDepartmentUpdateDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

TenantDepartmentUpdateDto<PSCustomObject>
#>
function ConvertFrom-JsonToTenantDepartmentUpdateDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => TenantDepartmentUpdateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in TenantDepartmentUpdateDto
        $AllProperties = ("name", "description", "disabled", "organizationProfileId", "parentDepartmentId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "disabled"))) { #optional property not found
            $Disabled = $null
        } else {
            $Disabled = $JsonParameters.PSobject.Properties["disabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "organizationProfileId"))) { #optional property not found
            $OrganizationProfileId = $null
        } else {
            $OrganizationProfileId = $JsonParameters.PSobject.Properties["organizationProfileId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "parentDepartmentId"))) { #optional property not found
            $ParentDepartmentId = $null
        } else {
            $ParentDepartmentId = $JsonParameters.PSobject.Properties["parentDepartmentId"].value
        }

        $PSO = [PSCustomObject]@{
            "name" = ${Name}
            "description" = ${Description}
            "disabled" = ${Disabled}
            "organizationProfileId" = ${OrganizationProfileId}
            "parentDepartmentId" = ${ParentDepartmentId}
        }

        return $PSO
    }

}

