#
# HrmsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.1.2.5401
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'SalaryUpdateDto' {
    Context 'SalaryUpdateDto' {
        It 'Initialize-SalaryUpdateDto' {
            # a simple test to create an object
            #$NewObject = Initialize-SalaryUpdateDto -Amount "TEST_VALUE" -CurrencyId "TEST_VALUE" -EmployeeProfileId "TEST_VALUE"
            #$NewObject | Should -BeOfType SalaryUpdateDto
            #$NewObject.property | Should -Be 0
        }
    }
}
