#
# WalletsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.1.2.5401
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Timestamp
No description available.
.PARAMETER RequestedWithdrawAmount
No description available.
.PARAMETER RequestedWithdrawAmountInUSD
No description available.
.PARAMETER WalletWithdrawRequestStatus
No description available.
.PARAMETER CurrencyId
No description available.
.PARAMETER BusinessId
No description available.
.PARAMETER WalletAccountId
No description available.
.PARAMETER BankAccountId
No description available.
.OUTPUTS

WalletWithdrawRequestDto<PSCustomObject>
#>

function Initialize-WalletWithdrawRequestDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${Timestamp},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${RequestedWithdrawAmount},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${RequestedWithdrawAmountInUSD},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("Pending", "Processed", "Cancelled", "OnHold", "Denied")]
        [String]
        ${WalletWithdrawRequestStatus},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CurrencyId},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BusinessId},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${WalletAccountId},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BankAccountId}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => WalletWithdrawRequestDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "requestedWithdrawAmount" = ${RequestedWithdrawAmount}
            "requestedWithdrawAmountInUSD" = ${RequestedWithdrawAmountInUSD}
            "walletWithdrawRequestStatus" = ${WalletWithdrawRequestStatus}
            "currencyId" = ${CurrencyId}
            "businessId" = ${BusinessId}
            "walletAccountId" = ${WalletAccountId}
            "bankAccountId" = ${BankAccountId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to WalletWithdrawRequestDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to WalletWithdrawRequestDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

WalletWithdrawRequestDto<PSCustomObject>
#>
function ConvertFrom-JsonToWalletWithdrawRequestDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => WalletWithdrawRequestDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in WalletWithdrawRequestDto
        $AllProperties = ("id", "timestamp", "requestedWithdrawAmount", "requestedWithdrawAmountInUSD", "walletWithdrawRequestStatus", "currencyId", "businessId", "walletAccountId", "bankAccountId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timestamp"))) { #optional property not found
            $Timestamp = $null
        } else {
            $Timestamp = $JsonParameters.PSobject.Properties["timestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "requestedWithdrawAmount"))) { #optional property not found
            $RequestedWithdrawAmount = $null
        } else {
            $RequestedWithdrawAmount = $JsonParameters.PSobject.Properties["requestedWithdrawAmount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "requestedWithdrawAmountInUSD"))) { #optional property not found
            $RequestedWithdrawAmountInUSD = $null
        } else {
            $RequestedWithdrawAmountInUSD = $JsonParameters.PSobject.Properties["requestedWithdrawAmountInUSD"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "walletWithdrawRequestStatus"))) { #optional property not found
            $WalletWithdrawRequestStatus = $null
        } else {
            $WalletWithdrawRequestStatus = $JsonParameters.PSobject.Properties["walletWithdrawRequestStatus"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "currencyId"))) { #optional property not found
            $CurrencyId = $null
        } else {
            $CurrencyId = $JsonParameters.PSobject.Properties["currencyId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "businessId"))) { #optional property not found
            $BusinessId = $null
        } else {
            $BusinessId = $JsonParameters.PSobject.Properties["businessId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "walletAccountId"))) { #optional property not found
            $WalletAccountId = $null
        } else {
            $WalletAccountId = $JsonParameters.PSobject.Properties["walletAccountId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bankAccountId"))) { #optional property not found
            $BankAccountId = $null
        } else {
            $BankAccountId = $JsonParameters.PSobject.Properties["bankAccountId"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "requestedWithdrawAmount" = ${RequestedWithdrawAmount}
            "requestedWithdrawAmountInUSD" = ${RequestedWithdrawAmountInUSD}
            "walletWithdrawRequestStatus" = ${WalletWithdrawRequestStatus}
            "currencyId" = ${CurrencyId}
            "businessId" = ${BusinessId}
            "walletAccountId" = ${WalletAccountId}
            "bankAccountId" = ${BankAccountId}
        }

        return $PSO
    }

}

