#
# ContentService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.1.2.5532
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'MenuContextItemDto' {
    Context 'MenuContextItemDto' {
        It 'Initialize-MenuContextItemDto' {
            # a simple test to create an object
            #$NewObject = Initialize-MenuContextItemDto -Id "TEST_VALUE" -Timestamp "TEST_VALUE" -Order "TEST_VALUE" -Name "TEST_VALUE" -Text "TEST_VALUE" -Url "TEST_VALUE" -Icon "TEST_VALUE" -Target "TEST_VALUE" -Tooltip "TEST_VALUE" -ParentMenuContextItemId "TEST_VALUE" -MenuContextId "TEST_VALUE"
            #$NewObject | Should -BeOfType MenuContextItemDto
            #$NewObject.property | Should -Be 0
        }
    }
}
