#
# ContentService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'WebPageTagUpdateDto' {
    Context 'WebPageTagUpdateDto' {
        It 'Initialize-WebPageTagUpdateDto' {
            # a simple test to create an object
            #$NewObject = Initialize-WebPageTagUpdateDto -Slug "TEST_VALUE" -Title "TEST_VALUE" -Description "TEST_VALUE" -SeoTitle "TEST_VALUE" -MetaDescription "TEST_VALUE" -CornerstoneContent "TEST_VALUE" -AllowSerachEngines "TEST_VALUE" -SeoKeyPhrases "TEST_VALUE" -CanonicalUrl "TEST_VALUE" -ImageURL "TEST_VALUE" -Image "TEST_VALUE"
            #$NewObject | Should -BeOfType WebPageTagUpdateDto
            #$NewObject.property | Should -Be 0
        }
    }
}
