#
# MarketingService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.1.4089
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'SocialMediaPostsApi' {
    Context 'Invoke-ApiV2MarketingServiceSocialMediaPostsCountGet' {
        It 'Test Invoke-ApiV2MarketingServiceSocialMediaPostsCountGet' {
            #$TestResult = Invoke-ApiV2MarketingServiceSocialMediaPostsCountGet -TenantId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ApiV2MarketingServiceSocialMediaPostsGet' {
        It 'Test Invoke-ApiV2MarketingServiceSocialMediaPostsGet' {
            #$TestResult = Invoke-ApiV2MarketingServiceSocialMediaPostsGet -TenantId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ApiV2MarketingServiceSocialMediaPostsPost' {
        It 'Test Invoke-ApiV2MarketingServiceSocialMediaPostsPost' {
            #$TestResult = Invoke-ApiV2MarketingServiceSocialMediaPostsPost -TenantId "TEST_VALUE" -SocialMediaPostCreateDto "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ApiV2MarketingServiceSocialMediaPostsSocialmediapostIdDelete' {
        It 'Test Invoke-ApiV2MarketingServiceSocialMediaPostsSocialmediapostIdDelete' {
            #$TestResult = Invoke-ApiV2MarketingServiceSocialMediaPostsSocialmediapostIdDelete -TenantId "TEST_VALUE" -SocialmediapostId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ApiV2MarketingServiceSocialMediaPostsSocialmediapostIdGet' {
        It 'Test Invoke-ApiV2MarketingServiceSocialMediaPostsSocialmediapostIdGet' {
            #$TestResult = Invoke-ApiV2MarketingServiceSocialMediaPostsSocialmediapostIdGet -TenantId "TEST_VALUE" -SocialmediapostId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ApiV2MarketingServiceSocialMediaPostsSocialmediapostIdPut' {
        It 'Test Invoke-ApiV2MarketingServiceSocialMediaPostsSocialmediapostIdPut' {
            #$TestResult = Invoke-ApiV2MarketingServiceSocialMediaPostsSocialmediapostIdPut -TenantId "TEST_VALUE" -SocialmediapostId "TEST_VALUE" -SocialMediaPostUpdateDto "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
