#
# BlockchainsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.1.2.5532
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'Module' {
    Context 'Module' {
        It 'Initialize-Module' {
            # a simple test to create an object
            #$NewObject = Initialize-Module -Assembly "TEST_VALUE" -FullyQualifiedName "TEST_VALUE" -Name "TEST_VALUE" -MdStreamVersion "TEST_VALUE" -ModuleVersionId "TEST_VALUE" -ScopeName "TEST_VALUE" -ModuleHandle "TEST_VALUE" -CustomAttributes "TEST_VALUE" -MetadataToken "TEST_VALUE"
            #$NewObject | Should -BeOfType Module
            #$NewObject.property | Should -Be 0
        }
    }
}
