#
# BlockchainsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.1.2.5532
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'WebSocketManager' {
    Context 'WebSocketManager' {
        It 'Initialize-WebSocketManager' {
            # a simple test to create an object
            #$NewObject = Initialize-WebSocketManager -IsWebSocketRequest "TEST_VALUE" -WebSocketRequestedProtocols "TEST_VALUE"
            #$NewObject | Should -BeOfType WebSocketManager
            #$NewObject.property | Should -Be 0
        }
    }
}
