#
# PaymentsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PaymentProviderRegistrationDtoListEnvelope' {
    Context 'PaymentProviderRegistrationDtoListEnvelope' {
        It 'Initialize-PaymentProviderRegistrationDtoListEnvelope' {
            # a simple test to create an object
            #$NewObject = Initialize-PaymentProviderRegistrationDtoListEnvelope -IsSuccess "TEST_VALUE" -ErrorMessage "TEST_VALUE" -CorrelationId "TEST_VALUE" -Timestamp "TEST_VALUE" -HttpStatus "TEST_VALUE" -ErrorCode "TEST_VALUE" -ValidationDetails "TEST_VALUE" -ActivityId "TEST_VALUE" -Result "TEST_VALUE"
            #$NewObject | Should -BeOfType PaymentProviderRegistrationDtoListEnvelope
            #$NewObject.property | Should -Be 0
        }
    }
}
