#
# LogisticsService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.1.2.5401
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ProofsOfDeliveryApi' {
    Context 'Add-ProofOfDeliveryLineAsync' {
        It 'Test Add-ProofOfDeliveryLineAsync' {
            #$TestResult = Add-ProofOfDeliveryLineAsync -TenantId "TEST_VALUE" -PodId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE" -ProofOfDeliveryLineCreateDto "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Add-DeliveryNoteAsync' {
        It 'Test Add-DeliveryNoteAsync' {
            #$TestResult = Add-DeliveryNoteAsync -TenantId "TEST_VALUE" -PodId "TEST_VALUE" -NoteId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-ProofOfDeliveryAsync' {
        It 'Test New-ProofOfDeliveryAsync' {
            #$TestResult = New-ProofOfDeliveryAsync -TenantId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE" -ProofOfDeliveryCreateDto "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeleteProofOfDeliveryAsync' {
        It 'Test Invoke-DeleteProofOfDeliveryAsync' {
            #$TestResult = Invoke-DeleteProofOfDeliveryAsync -TenantId "TEST_VALUE" -PodId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DetachDeliveryNoteAsync' {
        It 'Test Invoke-DetachDeliveryNoteAsync' {
            #$TestResult = Invoke-DetachDeliveryNoteAsync -TenantId "TEST_VALUE" -PodId "TEST_VALUE" -NoteId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DisputeProofOfDeliveryAsync' {
        It 'Test Invoke-DisputeProofOfDeliveryAsync' {
            #$TestResult = Invoke-DisputeProofOfDeliveryAsync -TenantId "TEST_VALUE" -PodId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE" -DisputeProofOfDeliveryRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ProofOfDeliveryByIdAsync' {
        It 'Test Get-ProofOfDeliveryByIdAsync' {
            #$TestResult = Get-ProofOfDeliveryByIdAsync -TenantId "TEST_VALUE" -PodId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ProofOfDeliveryDeliveryNotesAsync' {
        It 'Test Get-ProofOfDeliveryDeliveryNotesAsync' {
            #$TestResult = Get-ProofOfDeliveryDeliveryNotesAsync -TenantId "TEST_VALUE" -PodId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ProofOfDeliveryDeliveryNotesCountAsync' {
        It 'Test Get-ProofOfDeliveryDeliveryNotesCountAsync' {
            #$TestResult = Get-ProofOfDeliveryDeliveryNotesCountAsync -TenantId "TEST_VALUE" -PodId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ProofOfDeliveryLinesAsync' {
        It 'Test Get-ProofOfDeliveryLinesAsync' {
            #$TestResult = Get-ProofOfDeliveryLinesAsync -TenantId "TEST_VALUE" -PodId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ProofOfDeliveryLinesCountAsync' {
        It 'Test Get-ProofOfDeliveryLinesCountAsync' {
            #$TestResult = Get-ProofOfDeliveryLinesCountAsync -TenantId "TEST_VALUE" -PodId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ProofsOfDeliveryAsync' {
        It 'Test Get-ProofsOfDeliveryAsync' {
            #$TestResult = Get-ProofsOfDeliveryAsync -TenantId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ProofsOfDeliveryCountAsync' {
        It 'Test Get-ProofsOfDeliveryCountAsync' {
            #$TestResult = Get-ProofsOfDeliveryCountAsync -TenantId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Deny-ProofOfDeliveryAsync' {
        It 'Test Deny-ProofOfDeliveryAsync' {
            #$TestResult = Deny-ProofOfDeliveryAsync -TenantId "TEST_VALUE" -PodId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE" -RejectProofOfDeliveryRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Remove-ProofOfDeliveryLineAsync' {
        It 'Test Remove-ProofOfDeliveryLineAsync' {
            #$TestResult = Remove-ProofOfDeliveryLineAsync -TenantId "TEST_VALUE" -PodId "TEST_VALUE" -LineId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SignProofOfDeliveryAsync' {
        It 'Test Invoke-SignProofOfDeliveryAsync' {
            #$TestResult = Invoke-SignProofOfDeliveryAsync -TenantId "TEST_VALUE" -PodId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE" -SignProofOfDeliveryRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-ProofOfDeliveryAsync' {
        It 'Test Update-ProofOfDeliveryAsync' {
            #$TestResult = Update-ProofOfDeliveryAsync -TenantId "TEST_VALUE" -PodId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE" -ProofOfDeliveryUpdateDto "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-ProofOfDeliveryLineAsync' {
        It 'Test Update-ProofOfDeliveryLineAsync' {
            #$TestResult = Update-ProofOfDeliveryLineAsync -TenantId "TEST_VALUE" -PodId "TEST_VALUE" -LineId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE" -ProofOfDeliveryLineUpdateDto "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
