#
# SupportService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.1.4089
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'SupportTicketsApi' {
    Context 'Invoke-ApiV2SupportServiceSupportTicketsCountGet' {
        It 'Test Invoke-ApiV2SupportServiceSupportTicketsCountGet' {
            #$TestResult = Invoke-ApiV2SupportServiceSupportTicketsCountGet -TenantId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ApiV2SupportServiceSupportTicketsGet' {
        It 'Test Invoke-ApiV2SupportServiceSupportTicketsGet' {
            #$TestResult = Invoke-ApiV2SupportServiceSupportTicketsGet -TenantId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ApiV2SupportServiceSupportTicketsPost' {
        It 'Test Invoke-ApiV2SupportServiceSupportTicketsPost' {
            #$TestResult = Invoke-ApiV2SupportServiceSupportTicketsPost -SupportTicketCreateDto "TEST_VALUE" -TenantId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdConversationsGet' {
        It 'Test Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdConversationsGet' {
            #$TestResult = Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdConversationsGet -SupportTicketId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdConversationsPost' {
        It 'Test Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdConversationsPost' {
            #$TestResult = Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdConversationsPost -SupportTicketId "TEST_VALUE" -SupportTicketConversationCreateDto "TEST_VALUE" -TenantId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdConversationsSupportTicketConversationIdDelete' {
        It 'Test Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdConversationsSupportTicketConversationIdDelete' {
            #$TestResult = Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdConversationsSupportTicketConversationIdDelete -SupportTicketId "TEST_VALUE" -SupportTicketConversationId "TEST_VALUE" -TenantId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdConversationsSupportTicketConversationIdGet' {
        It 'Test Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdConversationsSupportTicketConversationIdGet' {
            #$TestResult = Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdConversationsSupportTicketConversationIdGet -SupportTicketId "TEST_VALUE" -SupportTicketConversationId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdConversationsSupportTicketConversationIdMessagesGet' {
        It 'Test Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdConversationsSupportTicketConversationIdMessagesGet' {
            #$TestResult = Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdConversationsSupportTicketConversationIdMessagesGet -SupportTicketConversationId "TEST_VALUE" -SupportTicketId "TEST_VALUE" -PageNumber "TEST_VALUE" -PageSize "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdDelete' {
        It 'Test Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdDelete' {
            #$TestResult = Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdDelete -SupportTicketId "TEST_VALUE" -TenantId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdGet' {
        It 'Test Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdGet' {
            #$TestResult = Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdGet -SupportTicketId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdPut' {
        It 'Test Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdPut' {
            #$TestResult = Invoke-ApiV2SupportServiceSupportTicketsSupportTicketIdPut -SupportTicketId "TEST_VALUE" -SupportTicketUpdateDto "TEST_VALUE" -TenantId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
