#
# CatalogService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Timestamp
No description available.
.PARAMETER Title
No description available.
.PARAMETER Description
No description available.
.PARAMETER ImageURL
No description available.
.PARAMETER IsFeatured
No description available.
.PARAMETER EnableForCourses
No description available.
.PARAMETER EnableForProducts
No description available.
.PARAMETER EnableForLicenses
No description available.
.PARAMETER EnableForServices
No description available.
.PARAMETER EnableForSubscriptions
No description available.
.PARAMETER BusinessID
No description available.
.PARAMETER BusinessProfileRecordID
No description available.
.PARAMETER ParentItemCategoryID
No description available.
.OUTPUTS

ItemCategoryDto<PSCustomObject>
#>

function Initialize-ItemCategoryDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${Timestamp},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Title},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ImageURL},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsFeatured},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${EnableForCourses},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${EnableForProducts},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${EnableForLicenses},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${EnableForServices},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${EnableForSubscriptions},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BusinessID},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BusinessProfileRecordID},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ParentItemCategoryID}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ItemCategoryDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "title" = ${Title}
            "description" = ${Description}
            "imageURL" = ${ImageURL}
            "isFeatured" = ${IsFeatured}
            "enableForCourses" = ${EnableForCourses}
            "enableForProducts" = ${EnableForProducts}
            "enableForLicenses" = ${EnableForLicenses}
            "enableForServices" = ${EnableForServices}
            "enableForSubscriptions" = ${EnableForSubscriptions}
            "businessID" = ${BusinessID}
            "businessProfileRecordID" = ${BusinessProfileRecordID}
            "parentItemCategoryID" = ${ParentItemCategoryID}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ItemCategoryDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to ItemCategoryDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ItemCategoryDto<PSCustomObject>
#>
function ConvertFrom-JsonToItemCategoryDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ItemCategoryDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ItemCategoryDto
        $AllProperties = ("id", "timestamp", "title", "description", "imageURL", "isFeatured", "enableForCourses", "enableForProducts", "enableForLicenses", "enableForServices", "enableForSubscriptions", "businessID", "businessProfileRecordID", "parentItemCategoryID")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timestamp"))) { #optional property not found
            $Timestamp = $null
        } else {
            $Timestamp = $JsonParameters.PSobject.Properties["timestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "title"))) { #optional property not found
            $Title = $null
        } else {
            $Title = $JsonParameters.PSobject.Properties["title"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "imageURL"))) { #optional property not found
            $ImageURL = $null
        } else {
            $ImageURL = $JsonParameters.PSobject.Properties["imageURL"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isFeatured"))) { #optional property not found
            $IsFeatured = $null
        } else {
            $IsFeatured = $JsonParameters.PSobject.Properties["isFeatured"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "enableForCourses"))) { #optional property not found
            $EnableForCourses = $null
        } else {
            $EnableForCourses = $JsonParameters.PSobject.Properties["enableForCourses"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "enableForProducts"))) { #optional property not found
            $EnableForProducts = $null
        } else {
            $EnableForProducts = $JsonParameters.PSobject.Properties["enableForProducts"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "enableForLicenses"))) { #optional property not found
            $EnableForLicenses = $null
        } else {
            $EnableForLicenses = $JsonParameters.PSobject.Properties["enableForLicenses"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "enableForServices"))) { #optional property not found
            $EnableForServices = $null
        } else {
            $EnableForServices = $JsonParameters.PSobject.Properties["enableForServices"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "enableForSubscriptions"))) { #optional property not found
            $EnableForSubscriptions = $null
        } else {
            $EnableForSubscriptions = $JsonParameters.PSobject.Properties["enableForSubscriptions"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "businessID"))) { #optional property not found
            $BusinessID = $null
        } else {
            $BusinessID = $JsonParameters.PSobject.Properties["businessID"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "businessProfileRecordID"))) { #optional property not found
            $BusinessProfileRecordID = $null
        } else {
            $BusinessProfileRecordID = $JsonParameters.PSobject.Properties["businessProfileRecordID"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "parentItemCategoryID"))) { #optional property not found
            $ParentItemCategoryID = $null
        } else {
            $ParentItemCategoryID = $JsonParameters.PSobject.Properties["parentItemCategoryID"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "title" = ${Title}
            "description" = ${Description}
            "imageURL" = ${ImageURL}
            "isFeatured" = ${IsFeatured}
            "enableForCourses" = ${EnableForCourses}
            "enableForProducts" = ${EnableForProducts}
            "enableForLicenses" = ${EnableForLicenses}
            "enableForServices" = ${EnableForServices}
            "enableForSubscriptions" = ${EnableForSubscriptions}
            "businessID" = ${BusinessID}
            "businessProfileRecordID" = ${BusinessProfileRecordID}
            "parentItemCategoryID" = ${ParentItemCategoryID}
        }

        return $PSO
    }

}

