#
# AccountingService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Title
No description available.
.PARAMETER Description
No description available.
.PARAMETER ParentAccountGroupId
No description available.
.PARAMETER TenantId
No description available.
.PARAMETER EnrollmentId
No description available.
.OUTPUTS

AccountGroupUpdateDto<PSCustomObject>
#>

function Initialize-AccountGroupUpdateDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Title},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ParentAccountGroupId},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TenantId},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${EnrollmentId}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => AccountGroupUpdateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Title -and $Title.length -gt 50) {
            throw "invalid value for 'Title', the character length must be smaller than or equal to 50."
        }

        if (!$Title -and $Title.length -lt 0) {
            throw "invalid value for 'Title', the character length must be great than or equal to 0."
        }

        if (!$Description -and $Description.length -gt 150) {
            throw "invalid value for 'Description', the character length must be smaller than or equal to 150."
        }

        if (!$Description -and $Description.length -lt 0) {
            throw "invalid value for 'Description', the character length must be great than or equal to 0."
        }

        if (!$ParentAccountGroupId -and $ParentAccountGroupId.length -gt 36) {
            throw "invalid value for 'ParentAccountGroupId', the character length must be smaller than or equal to 36."
        }

        if (!$ParentAccountGroupId -and $ParentAccountGroupId.length -lt 0) {
            throw "invalid value for 'ParentAccountGroupId', the character length must be great than or equal to 0."
        }

        if (!$TenantId -and $TenantId.length -gt 36) {
            throw "invalid value for 'TenantId', the character length must be smaller than or equal to 36."
        }

        if (!$TenantId -and $TenantId.length -lt 0) {
            throw "invalid value for 'TenantId', the character length must be great than or equal to 0."
        }

        if (!$EnrollmentId -and $EnrollmentId.length -gt 36) {
            throw "invalid value for 'EnrollmentId', the character length must be smaller than or equal to 36."
        }

        if (!$EnrollmentId -and $EnrollmentId.length -lt 0) {
            throw "invalid value for 'EnrollmentId', the character length must be great than or equal to 0."
        }


        $PSO = [PSCustomObject]@{
            "title" = ${Title}
            "description" = ${Description}
            "parentAccountGroupId" = ${ParentAccountGroupId}
            "tenantId" = ${TenantId}
            "enrollmentId" = ${EnrollmentId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AccountGroupUpdateDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to AccountGroupUpdateDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AccountGroupUpdateDto<PSCustomObject>
#>
function ConvertFrom-JsonToAccountGroupUpdateDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => AccountGroupUpdateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AccountGroupUpdateDto
        $AllProperties = ("title", "description", "parentAccountGroupId", "tenantId", "enrollmentId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "title"))) { #optional property not found
            $Title = $null
        } else {
            $Title = $JsonParameters.PSobject.Properties["title"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "parentAccountGroupId"))) { #optional property not found
            $ParentAccountGroupId = $null
        } else {
            $ParentAccountGroupId = $JsonParameters.PSobject.Properties["parentAccountGroupId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tenantId"))) { #optional property not found
            $TenantId = $null
        } else {
            $TenantId = $JsonParameters.PSobject.Properties["tenantId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "enrollmentId"))) { #optional property not found
            $EnrollmentId = $null
        } else {
            $EnrollmentId = $JsonParameters.PSobject.Properties["enrollmentId"].value
        }

        $PSO = [PSCustomObject]@{
            "title" = ${Title}
            "description" = ${Description}
            "parentAccountGroupId" = ${ParentAccountGroupId}
            "tenantId" = ${TenantId}
            "enrollmentId" = ${EnrollmentId}
        }

        return $PSO
    }

}

