#
# AccountingService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Timestamp
No description available.
.PARAMETER JournalId
No description available.
.PARAMETER FiscalPeriodId
No description available.
.PARAMETER TransactionCurrencyId
No description available.
.PARAMETER Description
No description available.
.PARAMETER SourceDocumentType
No description available.
.PARAMETER SourceDocumentId
No description available.
.PARAMETER IdempotencyKey
No description available.
.PARAMETER IsOpeningBalance
No description available.
.PARAMETER AccountingEntries
No description available.
.OUTPUTS

JournalEntryCreateDto<PSCustomObject>
#>

function Initialize-JournalEntryCreateDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${Timestamp},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${JournalId},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${FiscalPeriodId},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TransactionCurrencyId},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SourceDocumentType},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SourceDocumentId},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${IdempotencyKey},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsOpeningBalance},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${AccountingEntries}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => JournalEntryCreateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $JournalId) {
            throw "invalid value for 'JournalId', 'JournalId' cannot be null."
        }

        if ($JournalId.length -lt 1) {
            throw "invalid value for 'JournalId', the character length must be great than or equal to 1."
        }

        if ($null -eq $FiscalPeriodId) {
            throw "invalid value for 'FiscalPeriodId', 'FiscalPeriodId' cannot be null."
        }

        if ($FiscalPeriodId.length -lt 1) {
            throw "invalid value for 'FiscalPeriodId', the character length must be great than or equal to 1."
        }

        if ($null -eq $TransactionCurrencyId) {
            throw "invalid value for 'TransactionCurrencyId', 'TransactionCurrencyId' cannot be null."
        }

        if ($TransactionCurrencyId.length -lt 1) {
            throw "invalid value for 'TransactionCurrencyId', the character length must be great than or equal to 1."
        }

        if ($null -eq $Description) {
            throw "invalid value for 'Description', 'Description' cannot be null."
        }

        if ($Description.length -gt 300) {
            throw "invalid value for 'Description', the character length must be smaller than or equal to 300."
        }

        if ($Description.length -lt 1) {
            throw "invalid value for 'Description', the character length must be great than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "journalId" = ${JournalId}
            "fiscalPeriodId" = ${FiscalPeriodId}
            "transactionCurrencyId" = ${TransactionCurrencyId}
            "description" = ${Description}
            "sourceDocumentType" = ${SourceDocumentType}
            "sourceDocumentId" = ${SourceDocumentId}
            "idempotencyKey" = ${IdempotencyKey}
            "isOpeningBalance" = ${IsOpeningBalance}
            "accountingEntries" = ${AccountingEntries}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to JournalEntryCreateDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to JournalEntryCreateDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

JournalEntryCreateDto<PSCustomObject>
#>
function ConvertFrom-JsonToJournalEntryCreateDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => JournalEntryCreateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in JournalEntryCreateDto
        $AllProperties = ("id", "timestamp", "journalId", "fiscalPeriodId", "transactionCurrencyId", "description", "sourceDocumentType", "sourceDocumentId", "idempotencyKey", "isOpeningBalance", "accountingEntries")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'journalId' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "journalId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'journalId' missing."
        } else {
            $JournalId = $JsonParameters.PSobject.Properties["journalId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "fiscalPeriodId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'fiscalPeriodId' missing."
        } else {
            $FiscalPeriodId = $JsonParameters.PSobject.Properties["fiscalPeriodId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "transactionCurrencyId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'transactionCurrencyId' missing."
        } else {
            $TransactionCurrencyId = $JsonParameters.PSobject.Properties["transactionCurrencyId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) {
            throw "Error! JSON cannot be serialized due to the required property 'description' missing."
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timestamp"))) { #optional property not found
            $Timestamp = $null
        } else {
            $Timestamp = $JsonParameters.PSobject.Properties["timestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sourceDocumentType"))) { #optional property not found
            $SourceDocumentType = $null
        } else {
            $SourceDocumentType = $JsonParameters.PSobject.Properties["sourceDocumentType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sourceDocumentId"))) { #optional property not found
            $SourceDocumentId = $null
        } else {
            $SourceDocumentId = $JsonParameters.PSobject.Properties["sourceDocumentId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "idempotencyKey"))) { #optional property not found
            $IdempotencyKey = $null
        } else {
            $IdempotencyKey = $JsonParameters.PSobject.Properties["idempotencyKey"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isOpeningBalance"))) { #optional property not found
            $IsOpeningBalance = $null
        } else {
            $IsOpeningBalance = $JsonParameters.PSobject.Properties["isOpeningBalance"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "accountingEntries"))) { #optional property not found
            $AccountingEntries = $null
        } else {
            $AccountingEntries = $JsonParameters.PSobject.Properties["accountingEntries"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "journalId" = ${JournalId}
            "fiscalPeriodId" = ${FiscalPeriodId}
            "transactionCurrencyId" = ${TransactionCurrencyId}
            "description" = ${Description}
            "sourceDocumentType" = ${SourceDocumentType}
            "sourceDocumentId" = ${SourceDocumentId}
            "idempotencyKey" = ${IdempotencyKey}
            "isOpeningBalance" = ${IsOpeningBalance}
            "accountingEntries" = ${AccountingEntries}
        }

        return $PSO
    }

}

