#
# AccountingService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Title
No description available.
.PARAMETER Description
No description available.
.PARAMETER BaseAmount
No description available.
.PARAMETER AddedPercent
No description available.
.PARAMETER AddedAmount
No description available.
.PARAMETER TaxComission
No description available.
.PARAMETER TenantId
No description available.
.PARAMETER EnrollmentId
No description available.
.PARAMETER SalaryId
No description available.
.PARAMETER EmisorWalletAccountId
No description available.
.PARAMETER ReceiverWalletAccountId
No description available.
.PARAMETER EmisorContactId
No description available.
.PARAMETER ReceiverContactId
No description available.
.PARAMETER PaymentId
No description available.
.OUTPUTS

PaymentCommissionUpdateDto<PSCustomObject>
#>

function Initialize-PaymentCommissionUpdateDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Title},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${BaseAmount},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${AddedPercent},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${AddedAmount},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${TaxComission},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TenantId},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${EnrollmentId},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SalaryId},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${EmisorWalletAccountId},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ReceiverWalletAccountId},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${EmisorContactId},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ReceiverContactId},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${PaymentId}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => PaymentCommissionUpdateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Title -and $Title.length -gt 50) {
            throw "invalid value for 'Title', the character length must be smaller than or equal to 50."
        }

        if (!$Title -and $Title.length -lt 0) {
            throw "invalid value for 'Title', the character length must be great than or equal to 0."
        }

        if (!$Description -and $Description.length -gt 250) {
            throw "invalid value for 'Description', the character length must be smaller than or equal to 250."
        }

        if (!$Description -and $Description.length -lt 0) {
            throw "invalid value for 'Description', the character length must be great than or equal to 0."
        }

        if (!$TenantId -and $TenantId.length -gt 36) {
            throw "invalid value for 'TenantId', the character length must be smaller than or equal to 36."
        }

        if (!$TenantId -and $TenantId.length -lt 0) {
            throw "invalid value for 'TenantId', the character length must be great than or equal to 0."
        }

        if (!$EnrollmentId -and $EnrollmentId.length -gt 36) {
            throw "invalid value for 'EnrollmentId', the character length must be smaller than or equal to 36."
        }

        if (!$EnrollmentId -and $EnrollmentId.length -lt 0) {
            throw "invalid value for 'EnrollmentId', the character length must be great than or equal to 0."
        }

        if (!$SalaryId -and $SalaryId.length -gt 36) {
            throw "invalid value for 'SalaryId', the character length must be smaller than or equal to 36."
        }

        if (!$SalaryId -and $SalaryId.length -lt 0) {
            throw "invalid value for 'SalaryId', the character length must be great than or equal to 0."
        }

        if (!$EmisorWalletAccountId -and $EmisorWalletAccountId.length -gt 36) {
            throw "invalid value for 'EmisorWalletAccountId', the character length must be smaller than or equal to 36."
        }

        if (!$EmisorWalletAccountId -and $EmisorWalletAccountId.length -lt 0) {
            throw "invalid value for 'EmisorWalletAccountId', the character length must be great than or equal to 0."
        }

        if (!$ReceiverWalletAccountId -and $ReceiverWalletAccountId.length -gt 36) {
            throw "invalid value for 'ReceiverWalletAccountId', the character length must be smaller than or equal to 36."
        }

        if (!$ReceiverWalletAccountId -and $ReceiverWalletAccountId.length -lt 0) {
            throw "invalid value for 'ReceiverWalletAccountId', the character length must be great than or equal to 0."
        }

        if (!$EmisorContactId -and $EmisorContactId.length -gt 36) {
            throw "invalid value for 'EmisorContactId', the character length must be smaller than or equal to 36."
        }

        if (!$EmisorContactId -and $EmisorContactId.length -lt 0) {
            throw "invalid value for 'EmisorContactId', the character length must be great than or equal to 0."
        }

        if (!$ReceiverContactId -and $ReceiverContactId.length -gt 36) {
            throw "invalid value for 'ReceiverContactId', the character length must be smaller than or equal to 36."
        }

        if (!$ReceiverContactId -and $ReceiverContactId.length -lt 0) {
            throw "invalid value for 'ReceiverContactId', the character length must be great than or equal to 0."
        }

        if (!$PaymentId -and $PaymentId.length -gt 36) {
            throw "invalid value for 'PaymentId', the character length must be smaller than or equal to 36."
        }

        if (!$PaymentId -and $PaymentId.length -lt 0) {
            throw "invalid value for 'PaymentId', the character length must be great than or equal to 0."
        }


        $PSO = [PSCustomObject]@{
            "title" = ${Title}
            "description" = ${Description}
            "baseAmount" = ${BaseAmount}
            "addedPercent" = ${AddedPercent}
            "addedAmount" = ${AddedAmount}
            "taxComission" = ${TaxComission}
            "tenantId" = ${TenantId}
            "enrollmentId" = ${EnrollmentId}
            "salaryId" = ${SalaryId}
            "emisorWalletAccountId" = ${EmisorWalletAccountId}
            "receiverWalletAccountId" = ${ReceiverWalletAccountId}
            "emisorContactId" = ${EmisorContactId}
            "receiverContactId" = ${ReceiverContactId}
            "paymentId" = ${PaymentId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PaymentCommissionUpdateDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to PaymentCommissionUpdateDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PaymentCommissionUpdateDto<PSCustomObject>
#>
function ConvertFrom-JsonToPaymentCommissionUpdateDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => PaymentCommissionUpdateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PaymentCommissionUpdateDto
        $AllProperties = ("title", "description", "baseAmount", "addedPercent", "addedAmount", "taxComission", "tenantId", "enrollmentId", "salaryId", "emisorWalletAccountId", "receiverWalletAccountId", "emisorContactId", "receiverContactId", "paymentId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "title"))) { #optional property not found
            $Title = $null
        } else {
            $Title = $JsonParameters.PSobject.Properties["title"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "baseAmount"))) { #optional property not found
            $BaseAmount = $null
        } else {
            $BaseAmount = $JsonParameters.PSobject.Properties["baseAmount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "addedPercent"))) { #optional property not found
            $AddedPercent = $null
        } else {
            $AddedPercent = $JsonParameters.PSobject.Properties["addedPercent"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "addedAmount"))) { #optional property not found
            $AddedAmount = $null
        } else {
            $AddedAmount = $JsonParameters.PSobject.Properties["addedAmount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "taxComission"))) { #optional property not found
            $TaxComission = $null
        } else {
            $TaxComission = $JsonParameters.PSobject.Properties["taxComission"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tenantId"))) { #optional property not found
            $TenantId = $null
        } else {
            $TenantId = $JsonParameters.PSobject.Properties["tenantId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "enrollmentId"))) { #optional property not found
            $EnrollmentId = $null
        } else {
            $EnrollmentId = $JsonParameters.PSobject.Properties["enrollmentId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "salaryId"))) { #optional property not found
            $SalaryId = $null
        } else {
            $SalaryId = $JsonParameters.PSobject.Properties["salaryId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "emisorWalletAccountId"))) { #optional property not found
            $EmisorWalletAccountId = $null
        } else {
            $EmisorWalletAccountId = $JsonParameters.PSobject.Properties["emisorWalletAccountId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "receiverWalletAccountId"))) { #optional property not found
            $ReceiverWalletAccountId = $null
        } else {
            $ReceiverWalletAccountId = $JsonParameters.PSobject.Properties["receiverWalletAccountId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "emisorContactId"))) { #optional property not found
            $EmisorContactId = $null
        } else {
            $EmisorContactId = $JsonParameters.PSobject.Properties["emisorContactId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "receiverContactId"))) { #optional property not found
            $ReceiverContactId = $null
        } else {
            $ReceiverContactId = $JsonParameters.PSobject.Properties["receiverContactId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "paymentId"))) { #optional property not found
            $PaymentId = $null
        } else {
            $PaymentId = $JsonParameters.PSobject.Properties["paymentId"].value
        }

        $PSO = [PSCustomObject]@{
            "title" = ${Title}
            "description" = ${Description}
            "baseAmount" = ${BaseAmount}
            "addedPercent" = ${AddedPercent}
            "addedAmount" = ${AddedAmount}
            "taxComission" = ${TaxComission}
            "tenantId" = ${TenantId}
            "enrollmentId" = ${EnrollmentId}
            "salaryId" = ${SalaryId}
            "emisorWalletAccountId" = ${EmisorWalletAccountId}
            "receiverWalletAccountId" = ${ReceiverWalletAccountId}
            "emisorContactId" = ${EmisorContactId}
            "receiverContactId" = ${ReceiverContactId}
            "paymentId" = ${PaymentId}
        }

        return $PSO
    }

}

