#
# AccountingService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER PaymentId
No description available.
.PARAMETER ForexRate
No description available.
.PARAMETER TotalAmount
No description available.
.PARAMETER TotalAmountInUsd
No description available.
.PARAMETER Closed
No description available.
.PARAMETER CurrencyId
No description available.
.PARAMETER ContactId
No description available.
.PARAMETER OrderId
No description available.
.PARAMETER InvoiceId
No description available.
.OUTPUTS

ReceiptUpdateDto<PSCustomObject>
#>

function Initialize-ReceiptUpdateDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${PaymentId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${ForexRate},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${TotalAmount},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${TotalAmountInUsd},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Closed},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CurrencyId},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ContactId},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${OrderId},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${InvoiceId}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ReceiptUpdateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "paymentId" = ${PaymentId}
            "forexRate" = ${ForexRate}
            "totalAmount" = ${TotalAmount}
            "totalAmountInUsd" = ${TotalAmountInUsd}
            "closed" = ${Closed}
            "currencyId" = ${CurrencyId}
            "contactId" = ${ContactId}
            "orderId" = ${OrderId}
            "invoiceId" = ${InvoiceId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ReceiptUpdateDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to ReceiptUpdateDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ReceiptUpdateDto<PSCustomObject>
#>
function ConvertFrom-JsonToReceiptUpdateDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ReceiptUpdateDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ReceiptUpdateDto
        $AllProperties = ("paymentId", "forexRate", "totalAmount", "totalAmountInUsd", "closed", "currencyId", "contactId", "orderId", "invoiceId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "paymentId"))) { #optional property not found
            $PaymentId = $null
        } else {
            $PaymentId = $JsonParameters.PSobject.Properties["paymentId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "forexRate"))) { #optional property not found
            $ForexRate = $null
        } else {
            $ForexRate = $JsonParameters.PSobject.Properties["forexRate"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "totalAmount"))) { #optional property not found
            $TotalAmount = $null
        } else {
            $TotalAmount = $JsonParameters.PSobject.Properties["totalAmount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "totalAmountInUsd"))) { #optional property not found
            $TotalAmountInUsd = $null
        } else {
            $TotalAmountInUsd = $JsonParameters.PSobject.Properties["totalAmountInUsd"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "closed"))) { #optional property not found
            $Closed = $null
        } else {
            $Closed = $JsonParameters.PSobject.Properties["closed"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "currencyId"))) { #optional property not found
            $CurrencyId = $null
        } else {
            $CurrencyId = $JsonParameters.PSobject.Properties["currencyId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "contactId"))) { #optional property not found
            $ContactId = $null
        } else {
            $ContactId = $JsonParameters.PSobject.Properties["contactId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "orderId"))) { #optional property not found
            $OrderId = $null
        } else {
            $OrderId = $JsonParameters.PSobject.Properties["orderId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "invoiceId"))) { #optional property not found
            $InvoiceId = $null
        } else {
            $InvoiceId = $JsonParameters.PSobject.Properties["invoiceId"].value
        }

        $PSO = [PSCustomObject]@{
            "paymentId" = ${PaymentId}
            "forexRate" = ${ForexRate}
            "totalAmount" = ${TotalAmount}
            "totalAmountInUsd" = ${TotalAmountInUsd}
            "closed" = ${Closed}
            "currencyId" = ${CurrencyId}
            "contactId" = ${ContactId}
            "orderId" = ${OrderId}
            "invoiceId" = ${InvoiceId}
        }

        return $PSO
    }

}

