#
# MarketingService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.1.4089
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'EmailGroupCreateDto' {
    Context 'EmailGroupCreateDto' {
        It 'Initialize-EmailGroupCreateDto' {
            # a simple test to create an object
            #$NewObject = Initialize-EmailGroupCreateDto -Id "TEST_VALUE" -Timestamp "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -Enabled "TEST_VALUE" -TenantId "TEST_VALUE" -EnrolmentId "TEST_VALUE"
            #$NewObject | Should -BeOfType EmailGroupCreateDto
            #$NewObject.property | Should -Be 0
        }
    }
}
