#
# MarketingService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.1.4089
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'MarketingCampaignUpdateDto' {
    Context 'MarketingCampaignUpdateDto' {
        It 'Initialize-MarketingCampaignUpdateDto' {
            # a simple test to create an object
            #$NewObject = Initialize-MarketingCampaignUpdateDto -Name "TEST_VALUE" -Offer "TEST_VALUE" -Active "TEST_VALUE" -ProposedStart "TEST_VALUE" -ProposedEnd "TEST_VALUE" -ActualStart "TEST_VALUE" -ActualEnd "TEST_VALUE" -Code "TEST_VALUE" -AllocatedBudget "TEST_VALUE" -ActivityCost "TEST_VALUE" -MiscCost "TEST_VALUE" -ExpectedResponsePercent "TEST_VALUE" -MarketingAreaId "TEST_VALUE" -CurrencyId "TEST_VALUE" -TenantId "TEST_VALUE" -EnrolmentId "TEST_VALUE"
            #$NewObject | Should -BeOfType MarketingCampaignUpdateDto
            #$NewObject.property | Should -Be 0
        }
    }
}
