#
# ContentService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Email1
No description available.
.PARAMETER Email2
No description available.
.PARAMETER PhoneNumber1
No description available.
.PARAMETER PhoneNumber2
No description available.
.PARAMETER AddressLine1
No description available.
.PARAMETER AddressLine2
No description available.
.PARAMETER CityID
No description available.
.PARAMETER CountryStateID
No description available.
.PARAMETER CountryID
No description available.
.PARAMETER PostalCode
No description available.
.OUTPUTS

ContactOptions<PSCustomObject>
#>

function Initialize-ContactOptions {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Email1},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Email2},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${PhoneNumber1},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${PhoneNumber2},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${AddressLine1},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${AddressLine2},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CityID},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CountryStateID},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CountryID},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${PostalCode}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ContactOptions' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "email1" = ${Email1}
            "email2" = ${Email2}
            "phoneNumber1" = ${PhoneNumber1}
            "phoneNumber2" = ${PhoneNumber2}
            "addressLine1" = ${AddressLine1}
            "addressLine2" = ${AddressLine2}
            "cityID" = ${CityID}
            "countryStateID" = ${CountryStateID}
            "countryID" = ${CountryID}
            "postalCode" = ${PostalCode}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ContactOptions<PSCustomObject>

.DESCRIPTION

Convert from JSON to ContactOptions<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ContactOptions<PSCustomObject>
#>
function ConvertFrom-JsonToContactOptions {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ContactOptions' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ContactOptions
        $AllProperties = ("email1", "email2", "phoneNumber1", "phoneNumber2", "addressLine1", "addressLine2", "cityID", "countryStateID", "countryID", "postalCode")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "email1"))) { #optional property not found
            $Email1 = $null
        } else {
            $Email1 = $JsonParameters.PSobject.Properties["email1"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "email2"))) { #optional property not found
            $Email2 = $null
        } else {
            $Email2 = $JsonParameters.PSobject.Properties["email2"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "phoneNumber1"))) { #optional property not found
            $PhoneNumber1 = $null
        } else {
            $PhoneNumber1 = $JsonParameters.PSobject.Properties["phoneNumber1"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "phoneNumber2"))) { #optional property not found
            $PhoneNumber2 = $null
        } else {
            $PhoneNumber2 = $JsonParameters.PSobject.Properties["phoneNumber2"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "addressLine1"))) { #optional property not found
            $AddressLine1 = $null
        } else {
            $AddressLine1 = $JsonParameters.PSobject.Properties["addressLine1"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "addressLine2"))) { #optional property not found
            $AddressLine2 = $null
        } else {
            $AddressLine2 = $JsonParameters.PSobject.Properties["addressLine2"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "cityID"))) { #optional property not found
            $CityID = $null
        } else {
            $CityID = $JsonParameters.PSobject.Properties["cityID"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "countryStateID"))) { #optional property not found
            $CountryStateID = $null
        } else {
            $CountryStateID = $JsonParameters.PSobject.Properties["countryStateID"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "countryID"))) { #optional property not found
            $CountryID = $null
        } else {
            $CountryID = $JsonParameters.PSobject.Properties["countryID"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "postalCode"))) { #optional property not found
            $PostalCode = $null
        } else {
            $PostalCode = $JsonParameters.PSobject.Properties["postalCode"].value
        }

        $PSO = [PSCustomObject]@{
            "email1" = ${Email1}
            "email2" = ${Email2}
            "phoneNumber1" = ${PhoneNumber1}
            "phoneNumber2" = ${PhoneNumber2}
            "addressLine1" = ${AddressLine1}
            "addressLine2" = ${AddressLine2}
            "cityID" = ${CityID}
            "countryStateID" = ${CountryStateID}
            "countryID" = ${CountryID}
            "postalCode" = ${PostalCode}
        }

        return $PSO
    }

}

