#
# ContentService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Color
No description available.
.PARAMETER Title
No description available.
.PARAMETER Icon
No description available.
.PARAMETER IconColor
No description available.
.PARAMETER Favicon
No description available.
.OUTPUTS

DashboardOptions<PSCustomObject>
#>

function Initialize-DashboardOptions {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Color},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Title},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Icon},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${IconColor},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Favicon}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => DashboardOptions' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "color" = ${Color}
            "title" = ${Title}
            "icon" = ${Icon}
            "iconColor" = ${IconColor}
            "favicon" = ${Favicon}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to DashboardOptions<PSCustomObject>

.DESCRIPTION

Convert from JSON to DashboardOptions<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

DashboardOptions<PSCustomObject>
#>
function ConvertFrom-JsonToDashboardOptions {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => DashboardOptions' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in DashboardOptions
        $AllProperties = ("color", "title", "icon", "iconColor", "favicon")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "color"))) { #optional property not found
            $Color = $null
        } else {
            $Color = $JsonParameters.PSobject.Properties["color"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "title"))) { #optional property not found
            $Title = $null
        } else {
            $Title = $JsonParameters.PSobject.Properties["title"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "icon"))) { #optional property not found
            $Icon = $null
        } else {
            $Icon = $JsonParameters.PSobject.Properties["icon"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "iconColor"))) { #optional property not found
            $IconColor = $null
        } else {
            $IconColor = $JsonParameters.PSobject.Properties["iconColor"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "favicon"))) { #optional property not found
            $Favicon = $null
        } else {
            $Favicon = $JsonParameters.PSobject.Properties["favicon"].value
        }

        $PSO = [PSCustomObject]@{
            "color" = ${Color}
            "title" = ${Title}
            "icon" = ${Icon}
            "iconColor" = ${IconColor}
            "favicon" = ${Favicon}
        }

        return $PSO
    }

}

