#
# ContentService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Timestamp
No description available.
.PARAMETER Root
No description available.
.PARAMETER Title
No description available.
.PARAMETER Domain
No description available.
.PARAMETER Disabled
No description available.
.PARAMETER TenantId
No description available.
.PARAMETER Description
No description available.
.PARAMETER EnrollmentId
No description available.
.PARAMETER WebsiteThemeId
No description available.
.PARAMETER BusinessDomainId
No description available.
.PARAMETER BusinessPortalApplicationId
No description available.
.OUTPUTS

WebPortalDto<PSCustomObject>
#>

function Initialize-WebPortalDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${Timestamp},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Root},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Title},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Domain},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Disabled},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TenantId},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${EnrollmentId},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${WebsiteThemeId},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BusinessDomainId},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BusinessPortalApplicationId}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => WebPortalDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "root" = ${Root}
            "title" = ${Title}
            "domain" = ${Domain}
            "disabled" = ${Disabled}
            "tenantId" = ${TenantId}
            "description" = ${Description}
            "enrollmentId" = ${EnrollmentId}
            "websiteThemeId" = ${WebsiteThemeId}
            "businessDomainId" = ${BusinessDomainId}
            "businessPortalApplicationId" = ${BusinessPortalApplicationId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to WebPortalDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to WebPortalDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

WebPortalDto<PSCustomObject>
#>
function ConvertFrom-JsonToWebPortalDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => WebPortalDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in WebPortalDto
        $AllProperties = ("id", "timestamp", "root", "title", "domain", "disabled", "tenantId", "description", "enrollmentId", "websiteThemeId", "businessDomainId", "businessPortalApplicationId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timestamp"))) { #optional property not found
            $Timestamp = $null
        } else {
            $Timestamp = $JsonParameters.PSobject.Properties["timestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "root"))) { #optional property not found
            $Root = $null
        } else {
            $Root = $JsonParameters.PSobject.Properties["root"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "title"))) { #optional property not found
            $Title = $null
        } else {
            $Title = $JsonParameters.PSobject.Properties["title"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "domain"))) { #optional property not found
            $Domain = $null
        } else {
            $Domain = $JsonParameters.PSobject.Properties["domain"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "disabled"))) { #optional property not found
            $Disabled = $null
        } else {
            $Disabled = $JsonParameters.PSobject.Properties["disabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tenantId"))) { #optional property not found
            $TenantId = $null
        } else {
            $TenantId = $JsonParameters.PSobject.Properties["tenantId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "enrollmentId"))) { #optional property not found
            $EnrollmentId = $null
        } else {
            $EnrollmentId = $JsonParameters.PSobject.Properties["enrollmentId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "websiteThemeId"))) { #optional property not found
            $WebsiteThemeId = $null
        } else {
            $WebsiteThemeId = $JsonParameters.PSobject.Properties["websiteThemeId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "businessDomainId"))) { #optional property not found
            $BusinessDomainId = $null
        } else {
            $BusinessDomainId = $JsonParameters.PSobject.Properties["businessDomainId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "businessPortalApplicationId"))) { #optional property not found
            $BusinessPortalApplicationId = $null
        } else {
            $BusinessPortalApplicationId = $JsonParameters.PSobject.Properties["businessPortalApplicationId"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "timestamp" = ${Timestamp}
            "root" = ${Root}
            "title" = ${Title}
            "domain" = ${Domain}
            "disabled" = ${Disabled}
            "tenantId" = ${TenantId}
            "description" = ${Description}
            "enrollmentId" = ${EnrollmentId}
            "websiteThemeId" = ${WebsiteThemeId}
            "businessDomainId" = ${BusinessDomainId}
            "businessPortalApplicationId" = ${BusinessPortalApplicationId}
        }

        return $PSO
    }

}

