#
# SystemService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'OutboxAdminReasonDto' {
    Context 'OutboxAdminReasonDto' {
        It 'Initialize-OutboxAdminReasonDto' {
            # a simple test to create an object
            #$NewObject = Initialize-OutboxAdminReasonDto -Reason "TEST_VALUE"
            #$NewObject | Should -BeOfType OutboxAdminReasonDto
            #$NewObject.property | Should -Be 0
        }
    }
}
