#
# CatalogService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.0.0.0
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ItemTagCreateDto' {
    Context 'ItemTagCreateDto' {
        It 'Initialize-ItemTagCreateDto' {
            # a simple test to create an object
            #$NewObject = Initialize-ItemTagCreateDto -Id "TEST_VALUE" -Timestamp "TEST_VALUE" -Title "TEST_VALUE" -Description "TEST_VALUE" -BusinessID "TEST_VALUE"
            #$NewObject | Should -BeOfType ItemTagCreateDto
            #$NewObject.property | Should -Be 0
        }
    }
}
