#
# SystemService
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 2.1.2.5257
# Contact: support@fenix-alliance.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'OptionsApi' {
    Context 'New-SystemOption' {
        It 'Test New-SystemOption' {
            #$TestResult = New-SystemOption -Key "TEST_VALUE" -PortalId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE" -OptionCreateDto "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeleteSystemOption' {
        It 'Test Invoke-DeleteSystemOption' {
            #$TestResult = Invoke-DeleteSystemOption -OptionId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SystemOptionById' {
        It 'Test Get-SystemOptionById' {
            #$TestResult = Get-SystemOptionById -OptionId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SystemOptionByKey' {
        It 'Test Get-SystemOptionByKey' {
            #$TestResult = Get-SystemOptionByKey -PortalId "TEST_VALUE" -Key "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SystemOptions' {
        It 'Test Get-SystemOptions' {
            #$TestResult = Get-SystemOptions -PortalId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SystemOptionsCount' {
        It 'Test Get-SystemOptionsCount' {
            #$TestResult = Get-SystemOptionsCount -PortalId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-SystemOption' {
        It 'Test Update-SystemOption' {
            #$TestResult = Update-SystemOption -OptionId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE" -OptionUpdateDto "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-UpsertSystemOption' {
        It 'Test Invoke-UpsertSystemOption' {
            #$TestResult = Invoke-UpsertSystemOption -Key "TEST_VALUE" -PortalId "TEST_VALUE" -ApiVersion "TEST_VALUE" -XApiVersion "TEST_VALUE" -OptionUpdateDto "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
